/*
 * generated by Xtext
 */
package org.moflon.tgg.mosl;

import org.eclipse.xtext.scoping.IScopeProvider;
import org.eclipse.xtext.validation.CompositeEValidator;
import org.moflon.tgg.mosl.scoping.TGGScopeProvider;

import com.google.inject.Binder;
import com.google.inject.name.Names;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TGGRuntimeModule extends org.moflon.tgg.mosl.AbstractTGGRuntimeModule {
	
	@Override
	public Class<? extends IScopeProvider> bindIScopeProvider() {
		return TGGScopeProvider.class;
	}
	
	@Override
	public void configure(final Binder binder) {
		super.configure(binder);
		// The ugliest hack ever to temporarily solve issue #781 (EObjectValidator has been switched off completely :-))
		// TODO TGG compiler or specification should be refactored on a long run to avoid the creation of TGG models that are not conform to the metamodel
		binder.bind(Boolean.class).annotatedWith(Names.named(CompositeEValidator.USE_EOBJECT_VALIDATOR)).toInstance(Boolean.FALSE);
	}
}
