/*
 * generated by Xtext
 */
package org.moflon.tgg.mosl;

import org.eclipse.xtext.scoping.IScopeProvider;
import org.moflon.tgg.mosl.scoping.TGGScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TGGRuntimeModule extends org.moflon.tgg.mosl.AbstractTGGRuntimeModule {
	
	@Override
	public Class<? extends IScopeProvider> bindIScopeProvider() {
		return TGGScopeProvider.class;
	}
	
}
