<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="org.moflon.sdm.constraints.democles" nsURI="platform:/plugin/org.moflon.sdm.constraints.democles/model/Democles.ecore" nsPrefix="org.moflon.sdm.constraints.democles">
  <eClassifiers xsi:type="ecore:EClass" name="AttributeVariableConstraint">
    <eSuperTypes href="http://gervarro.org/democles/specification.ecore#//Constraint"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="predicateSymbol" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeValueConstraint">
    <eSuperTypes href="http://gervarro.org/democles/constraint/emf.ecore#//EMFConstraint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypedConstant">
    <eSuperTypes href="http://gervarro.org/democles/specification.ecore#//Constant"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eClassifier">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EClassifier"/>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
