<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="SokobanCodeAdapter" nsURI="http://www.moflon.org.SokobanCodeAdapter" nsPrefix="SokobanCodeAdapter">
  <eClassifiers xsi:type="ecore:EClass" name="NodeToBoard">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source">
      <eType xsi:type="ecore:EClass" href="http://www.moflon.org.MocaTree#//Node"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target">
      <eType xsi:type="ecore:EClass" href="http://www.moflon.org.SokobanLanguage#//Board"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeToFloor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source">
      <eType xsi:type="ecore:EClass" href="http://www.moflon.org.MocaTree#//Node"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target">
      <eType xsi:type="ecore:EClass" href="http://www.moflon.org.SokobanLanguage#//Floor"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eSubpackages name="Rules" nsURI="http://www.moflon.org.SokobanCodeAdapter.Rules" nsPrefix="Rules">
    <eClassifiers xsi:type="ecore:EClass" name="AdminNodeToFigureRule">
      <eSuperTypes href="http://www.moflon.org.TGGRuntime#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AllOtherNodeToFloorRule">
      <eSuperTypes href="http://www.moflon.org.TGGRuntime#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BoardNodeToBoardRule">
      <eSuperTypes href="http://www.moflon.org.TGGRuntime#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="GoalNodeToFigureRule">
      <eSuperTypes href="http://www.moflon.org.TGGRuntime#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LeftcolumnNodeToFloorRule">
      <eSuperTypes href="http://www.moflon.org.TGGRuntime#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ServerNodeToFigureRule">
      <eSuperTypes href="http://www.moflon.org.TGGRuntime#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TopRowNodeToFloorRule">
      <eSuperTypes href="http://www.moflon.org.TGGRuntime#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WallNodeToFigureRule">
      <eSuperTypes href="http://www.moflon.org.TGGRuntime#//AbstractRule"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
