<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:activities="platform:/plugin/SDMLanguage/model/SDMLanguage.ecore#//activities" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:expressions="platform:/plugin/SDMLanguage/model/SDMLanguage.ecore#//expressions" name="rbac" nsURI="platform:/plugin/org.moflon.maave.tests.lang.rbac/model/Rbac.ecore" nsPrefix="org.moflon.maave.tests.lang.rbac">
  <eClassifiers xsi:type="ecore:EClass" name="SsdRelation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ssdExclusiveRoles" upperBound="-1" eType="//Role" eOpposite="//Role/ssdRelation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="User" eSuperTypes="//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="userSessions" upperBound="-1" eType="//Session" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="-1" eType="//Role" eOpposite="//Role/users"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nrOfSessions" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PermSsd">
    <eStructuralFeatures xsi:type="ecore:EReference" name="permission" lowerBound="2" upperBound="-1" eType="//Permission"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation" eSuperTypes="//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="DsdRelation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsdExclusiveRole" upperBound="-1" eType="//Role" eOpposite="//Role/dsdRelation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Session">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sessionRoles" upperBound="-1" eType="//Role" eOpposite="//Role/sessions"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nrOfActivatedRoles" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role" eSuperTypes="//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sessions" upperBound="-1" eType="//Session" eOpposite="//Session/sessionRoles"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsdRelation" upperBound="-1" eType="//DsdRelation" eOpposite="//DsdRelation/dsdExclusiveRole"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="users" upperBound="-1" eType="//User" eOpposite="//User/roles"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ssdRelation" upperBound="-1" eType="//SsdRelation" eOpposite="//SsdRelation/ssdExclusiveRoles"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="permissions" upperBound="-1" eType="//Permission" eOpposite="//Permission/roles"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="seniorRoles" upperBound="-1" eType="//Role" eOpposite="//Role/juniorRoles"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="juniorRoles" upperBound="-1" eType="//Role" eOpposite="//Role/seniorRoles"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Object" eSuperTypes="//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="RbacPolicy">
    <eOperations xsi:type="activities:MoflonEOperation" name="__validateSSD">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eParameters name="roleA" eType="//Role"/>
      <activity owningOperation="//RbacPolicy/__validateSSD">
        <ownedActivityNode xsi:type="activities:StoryNode" name="ActivityNode1" comment="ActivityNode1" outgoing="//RbacPolicy/__validateSSD/@activity/@ownedActivityEdge.0 //RbacPolicy/__validateSSD/@activity/@ownedActivityEdge.1" incoming="//RbacPolicy/__validateSSD/@activity/@ownedActivityEdge.2">
          <storyPattern comment="ActivityNode1">
            <objectVariable type="//SsdRelation" name="ssdRelation" outgoingLink="//RbacPolicy/__validateSSD/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.1 //RbacPolicy/__validateSSD/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.3"/>
            <objectVariable type="//Role" name="roleA" incomingLink="//RbacPolicy/__validateSSD/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.0 //RbacPolicy/__validateSSD/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.1" bindingState="BOUND"/>
            <objectVariable type="//User" name="userA" outgoingLink="//RbacPolicy/__validateSSD/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.2 //RbacPolicy/__validateSSD/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.0"/>
            <objectVariable type="//Role" name="roleB" incomingLink="//RbacPolicy/__validateSSD/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.2 //RbacPolicy/__validateSSD/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.3"/>
            <linkVariable name="roles" target="//RbacPolicy/__validateSSD/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.1" source="//RbacPolicy/__validateSSD/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.2" type="//User/roles"/>
            <linkVariable name="ssdExclusiveRoles" target="//RbacPolicy/__validateSSD/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.1" source="//RbacPolicy/__validateSSD/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.0" type="//SsdRelation/ssdExclusiveRoles"/>
            <linkVariable name="roles" target="//RbacPolicy/__validateSSD/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.3" source="//RbacPolicy/__validateSSD/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.2" type="//User/roles"/>
            <linkVariable name="ssdExclusiveRoles" target="//RbacPolicy/__validateSSD/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.3" source="//RbacPolicy/__validateSSD/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.0" type="//SsdRelation/ssdExclusiveRoles"/>
          </storyPattern>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StopNode" incoming="//RbacPolicy/__validateSSD/@activity/@ownedActivityEdge.1">
          <returnValue xsi:type="expressions:LiteralExpression" value="true"/>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StartNode" outgoing="//RbacPolicy/__validateSSD/@activity/@ownedActivityEdge.2"/>
        <ownedActivityNode xsi:type="activities:StopNode" incoming="//RbacPolicy/__validateSSD/@activity/@ownedActivityEdge.0">
          <returnValue xsi:type="expressions:LiteralExpression" value="false"/>
        </ownedActivityNode>
        <ownedActivityEdge source="//RbacPolicy/__validateSSD/@activity/@ownedActivityNode.0" target="//RbacPolicy/__validateSSD/@activity/@ownedActivityNode.3" guard="SUCCESS"/>
        <ownedActivityEdge source="//RbacPolicy/__validateSSD/@activity/@ownedActivityNode.0" target="//RbacPolicy/__validateSSD/@activity/@ownedActivityNode.1" guard="FAILURE"/>
        <ownedActivityEdge source="//RbacPolicy/__validateSSD/@activity/@ownedActivityNode.2" target="//RbacPolicy/__validateSSD/@activity/@ownedActivityNode.0"/>
      </activity>
    </eOperations>
    <eOperations xsi:type="activities:MoflonEOperation" name="addUserToRole">
      <eParameters name="user" eType="//User"/>
      <eParameters name="role" eType="//Role"/>
      <activity owningOperation="//RbacPolicy/addUserToRole">
        <ownedActivityNode xsi:type="activities:StartNode" outgoing="//RbacPolicy/addUserToRole/@activity/@ownedActivityEdge.0"/>
        <ownedActivityNode xsi:type="activities:StoryNode" name="ActivityNode2" comment="ActivityNode2" outgoing="//RbacPolicy/addUserToRole/@activity/@ownedActivityEdge.1" incoming="//RbacPolicy/addUserToRole/@activity/@ownedActivityEdge.0">
          <storyPattern comment="ActivityNode2">
            <objectVariable type="//Role" name="role" incomingLink="//RbacPolicy/addUserToRole/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.0" bindingState="BOUND"/>
            <objectVariable type="//User" name="user" outgoingLink="//RbacPolicy/addUserToRole/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.0" bindingState="BOUND"/>
            <linkVariable name="roles" target="//RbacPolicy/addUserToRole/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.0" source="//RbacPolicy/addUserToRole/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.1" type="//User/roles" bindingOperator="CREATE"/>
          </storyPattern>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StopNode" incoming="//RbacPolicy/addUserToRole/@activity/@ownedActivityEdge.1"/>
        <ownedActivityEdge source="//RbacPolicy/addUserToRole/@activity/@ownedActivityNode.0" target="//RbacPolicy/addUserToRole/@activity/@ownedActivityNode.1"/>
        <ownedActivityEdge source="//RbacPolicy/addUserToRole/@activity/@ownedActivityNode.1" target="//RbacPolicy/addUserToRole/@activity/@ownedActivityNode.2"/>
      </activity>
    </eOperations>
    <eOperations xsi:type="activities:MoflonEOperation" name="__validateDSD">
      <eParameters name="aRoleA" eType="//Role"/>
      <activity owningOperation="//RbacPolicy/__validateDSD">
        <ownedActivityNode xsi:type="activities:StopNode" incoming="//RbacPolicy/__validateDSD/@activity/@ownedActivityEdge.1"/>
        <ownedActivityNode xsi:type="activities:StartNode" outgoing="//RbacPolicy/__validateDSD/@activity/@ownedActivityEdge.0"/>
        <ownedActivityNode xsi:type="activities:StoryNode" name="ActivityNode3" comment="ActivityNode3" outgoing="//RbacPolicy/__validateDSD/@activity/@ownedActivityEdge.1" incoming="//RbacPolicy/__validateDSD/@activity/@ownedActivityEdge.0">
          <storyPattern comment="ActivityNode3">
            <objectVariable type="//Role" name="aRoleB" incomingLink="//RbacPolicy/__validateDSD/@activity/@ownedActivityNode.2/@storyPattern/@linkVariable.2" outgoingLink="//RbacPolicy/__validateDSD/@activity/@ownedActivityNode.2/@storyPattern/@linkVariable.0"/>
            <objectVariable type="//Session" name="aSession" outgoingLink="//RbacPolicy/__validateDSD/@activity/@ownedActivityNode.2/@storyPattern/@linkVariable.1 //RbacPolicy/__validateDSD/@activity/@ownedActivityNode.2/@storyPattern/@linkVariable.2"/>
            <objectVariable type="//Role" name="aRoleA" incomingLink="//RbacPolicy/__validateDSD/@activity/@ownedActivityNode.2/@storyPattern/@linkVariable.1" outgoingLink="//RbacPolicy/__validateDSD/@activity/@ownedActivityNode.2/@storyPattern/@linkVariable.3" bindingState="BOUND"/>
            <objectVariable type="//DsdRelation" name="aDsdRelation" incomingLink="//RbacPolicy/__validateDSD/@activity/@ownedActivityNode.2/@storyPattern/@linkVariable.0 //RbacPolicy/__validateDSD/@activity/@ownedActivityNode.2/@storyPattern/@linkVariable.3"/>
            <linkVariable name="dsdRelation" target="//RbacPolicy/__validateDSD/@activity/@ownedActivityNode.2/@storyPattern/@objectVariable.3" source="//RbacPolicy/__validateDSD/@activity/@ownedActivityNode.2/@storyPattern/@objectVariable.0" type="//Role/dsdRelation"/>
            <linkVariable name="sessionRoles" target="//RbacPolicy/__validateDSD/@activity/@ownedActivityNode.2/@storyPattern/@objectVariable.2" source="//RbacPolicy/__validateDSD/@activity/@ownedActivityNode.2/@storyPattern/@objectVariable.1" type="//Session/sessionRoles"/>
            <linkVariable name="sessionRoles" target="//RbacPolicy/__validateDSD/@activity/@ownedActivityNode.2/@storyPattern/@objectVariable.0" source="//RbacPolicy/__validateDSD/@activity/@ownedActivityNode.2/@storyPattern/@objectVariable.1" type="//Session/sessionRoles"/>
            <linkVariable name="dsdRelation" target="//RbacPolicy/__validateDSD/@activity/@ownedActivityNode.2/@storyPattern/@objectVariable.3" source="//RbacPolicy/__validateDSD/@activity/@ownedActivityNode.2/@storyPattern/@objectVariable.2" type="//Role/dsdRelation"/>
          </storyPattern>
        </ownedActivityNode>
        <ownedActivityEdge source="//RbacPolicy/__validateDSD/@activity/@ownedActivityNode.1" target="//RbacPolicy/__validateDSD/@activity/@ownedActivityNode.2"/>
        <ownedActivityEdge source="//RbacPolicy/__validateDSD/@activity/@ownedActivityNode.2" target="//RbacPolicy/__validateDSD/@activity/@ownedActivityNode.0"/>
      </activity>
    </eOperations>
    <eOperations xsi:type="activities:MoflonEOperation" name="activateRole">
      <eParameters name="role" eType="//Role"/>
      <eParameters name="session" eType="//Session"/>
      <eParameters name="user" eType="//User"/>
      <activity owningOperation="//RbacPolicy/activateRole">
        <ownedActivityNode xsi:type="activities:StartNode" outgoing="//RbacPolicy/activateRole/@activity/@ownedActivityEdge.0"/>
        <ownedActivityNode xsi:type="activities:StoryNode" name="ActivityNode4" comment="ActivityNode4" outgoing="//RbacPolicy/activateRole/@activity/@ownedActivityEdge.1" incoming="//RbacPolicy/activateRole/@activity/@ownedActivityEdge.0">
          <storyPattern comment="ActivityNode4">
            <objectVariable type="//User" name="user" outgoingLink="//RbacPolicy/activateRole/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.0 //RbacPolicy/activateRole/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.1" bindingState="BOUND"/>
            <objectVariable type="//Role" name="role" incomingLink="//RbacPolicy/activateRole/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.0 //RbacPolicy/activateRole/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.2" bindingState="BOUND"/>
            <objectVariable type="//Session" name="session" incomingLink="//RbacPolicy/activateRole/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.1" outgoingLink="//RbacPolicy/activateRole/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.2" bindingState="BOUND"/>
            <linkVariable name="roles" target="//RbacPolicy/activateRole/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.1" source="//RbacPolicy/activateRole/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.0" type="//User/roles"/>
            <linkVariable name="userSessions" target="//RbacPolicy/activateRole/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.2" source="//RbacPolicy/activateRole/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.0" type="//User/userSessions"/>
            <linkVariable name="sessionRoles" target="//RbacPolicy/activateRole/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.1" source="//RbacPolicy/activateRole/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.2" type="//Session/sessionRoles" bindingOperator="CREATE"/>
          </storyPattern>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StopNode" incoming="//RbacPolicy/activateRole/@activity/@ownedActivityEdge.1"/>
        <ownedActivityEdge source="//RbacPolicy/activateRole/@activity/@ownedActivityNode.0" target="//RbacPolicy/activateRole/@activity/@ownedActivityNode.1"/>
        <ownedActivityEdge source="//RbacPolicy/activateRole/@activity/@ownedActivityNode.1" target="//RbacPolicy/activateRole/@activity/@ownedActivityNode.2"/>
      </activity>
    </eOperations>
    <eOperations xsi:type="activities:MoflonEOperation" name="addUserToRoleCorrect">
      <eParameters name="role" eType="//Role"/>
      <eParameters name="user" eType="//User"/>
      <activity owningOperation="//RbacPolicy/addUserToRoleCorrect">
        <ownedActivityNode xsi:type="activities:StoryNode" name="ActivityNode5" comment="ActivityNode5" outgoing="//RbacPolicy/addUserToRoleCorrect/@activity/@ownedActivityEdge.0" incoming="//RbacPolicy/addUserToRoleCorrect/@activity/@ownedActivityEdge.1">
          <storyPattern comment="ActivityNode5">
            <objectVariable type="//Role" name="role" incomingLink="//RbacPolicy/addUserToRoleCorrect/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.1 //RbacPolicy/addUserToRoleCorrect/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.2" bindingState="BOUND"/>
            <objectVariable type="//Role" name="otherRole" incomingLink="//RbacPolicy/addUserToRoleCorrect/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.3 //RbacPolicy/addUserToRoleCorrect/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.0"/>
            <objectVariable type="//SsdRelation" name="ssdRelation" outgoingLink="//RbacPolicy/addUserToRoleCorrect/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.1 //RbacPolicy/addUserToRoleCorrect/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.0"/>
            <objectVariable type="//User" name="user" outgoingLink="//RbacPolicy/addUserToRoleCorrect/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.2 //RbacPolicy/addUserToRoleCorrect/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.3" bindingState="BOUND"/>
            <linkVariable name="ssdExclusiveRoles" target="//RbacPolicy/addUserToRoleCorrect/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.1" source="//RbacPolicy/addUserToRoleCorrect/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.2" type="//SsdRelation/ssdExclusiveRoles"/>
            <linkVariable name="ssdExclusiveRoles" target="//RbacPolicy/addUserToRoleCorrect/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.0" source="//RbacPolicy/addUserToRoleCorrect/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.2" type="//SsdRelation/ssdExclusiveRoles"/>
            <linkVariable name="roles" target="//RbacPolicy/addUserToRoleCorrect/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.0" source="//RbacPolicy/addUserToRoleCorrect/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.3" type="//User/roles" bindingOperator="CREATE"/>
            <linkVariable name="roles" target="//RbacPolicy/addUserToRoleCorrect/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.1" source="//RbacPolicy/addUserToRoleCorrect/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.3" type="//User/roles"/>
          </storyPattern>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StopNode" incoming="//RbacPolicy/addUserToRoleCorrect/@activity/@ownedActivityEdge.0"/>
        <ownedActivityNode xsi:type="activities:StartNode" outgoing="//RbacPolicy/addUserToRoleCorrect/@activity/@ownedActivityEdge.1"/>
        <ownedActivityEdge source="//RbacPolicy/addUserToRoleCorrect/@activity/@ownedActivityNode.0" target="//RbacPolicy/addUserToRoleCorrect/@activity/@ownedActivityNode.1"/>
        <ownedActivityEdge source="//RbacPolicy/addUserToRoleCorrect/@activity/@ownedActivityNode.2" target="//RbacPolicy/addUserToRoleCorrect/@activity/@ownedActivityNode.0"/>
      </activity>
    </eOperations>
    <eOperations xsi:type="activities:MoflonEOperation" name="activateRole">
      <eParameters name="user" eType="//User"/>
      <eParameters name="role" eType="//Role"/>
      <eParameters name="session" eType="//Session"/>
      <activity owningOperation="//RbacPolicy/activateRole.1">
        <ownedActivityNode xsi:type="activities:StoryNode" name="ActivityNode6" comment="ActivityNode6" outgoing="//RbacPolicy/activateRole.1/@activity/@ownedActivityEdge.0" incoming="//RbacPolicy/activateRole.1/@activity/@ownedActivityEdge.1">
          <storyPattern comment="ActivityNode6">
            <objectVariable type="//User" name="user" outgoingLink="//RbacPolicy/activateRole.1/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.0 //RbacPolicy/activateRole.1/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.1" bindingState="BOUND"/>
            <objectVariable type="//Session" name="session" incomingLink="//RbacPolicy/activateRole.1/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.1" outgoingLink="//RbacPolicy/activateRole.1/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.2" bindingState="BOUND"/>
            <objectVariable type="//Role" name="role" incomingLink="//RbacPolicy/activateRole.1/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.0 //RbacPolicy/activateRole.1/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.2" bindingState="BOUND"/>
            <linkVariable name="roles" target="//RbacPolicy/activateRole.1/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.2" source="//RbacPolicy/activateRole.1/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.0" type="//User/roles"/>
            <linkVariable name="userSessions" target="//RbacPolicy/activateRole.1/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.1" source="//RbacPolicy/activateRole.1/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.0" type="//User/userSessions"/>
            <linkVariable name="sessionRoles" target="//RbacPolicy/activateRole.1/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.2" source="//RbacPolicy/activateRole.1/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.1" type="//Session/sessionRoles" bindingOperator="CREATE"/>
          </storyPattern>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StartNode" outgoing="//RbacPolicy/activateRole.1/@activity/@ownedActivityEdge.1"/>
        <ownedActivityNode xsi:type="activities:StopNode" incoming="//RbacPolicy/activateRole.1/@activity/@ownedActivityEdge.0"/>
        <ownedActivityEdge source="//RbacPolicy/activateRole.1/@activity/@ownedActivityNode.0" target="//RbacPolicy/activateRole.1/@activity/@ownedActivityNode.2"/>
        <ownedActivityEdge source="//RbacPolicy/activateRole.1/@activity/@ownedActivityNode.1" target="//RbacPolicy/activateRole.1/@activity/@ownedActivityNode.0"/>
      </activity>
    </eOperations>
    <eOperations xsi:type="activities:MoflonEOperation" name="createSession">
      <eParameters name="user" eType="//User"/>
      <activity owningOperation="//RbacPolicy/createSession">
        <ownedActivityNode xsi:type="activities:StopNode" incoming="//RbacPolicy/createSession/@activity/@ownedActivityEdge.0"/>
        <ownedActivityNode xsi:type="activities:StoryNode" name="ActivityNode7" comment="ActivityNode7" outgoing="//RbacPolicy/createSession/@activity/@ownedActivityEdge.0" incoming="//RbacPolicy/createSession/@activity/@ownedActivityEdge.1">
          <storyPattern comment="ActivityNode7">
            <objectVariable type="//Session" name="session" incomingLink="//RbacPolicy/createSession/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.0" bindingOperator="CREATE"/>
            <objectVariable type="//User" name="user" outgoingLink="//RbacPolicy/createSession/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.0" bindingState="BOUND"/>
            <linkVariable name="userSessions" target="//RbacPolicy/createSession/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.0" source="//RbacPolicy/createSession/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.1" type="//User/userSessions" bindingOperator="CREATE"/>
          </storyPattern>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StartNode" outgoing="//RbacPolicy/createSession/@activity/@ownedActivityEdge.1"/>
        <ownedActivityEdge source="//RbacPolicy/createSession/@activity/@ownedActivityNode.1" target="//RbacPolicy/createSession/@activity/@ownedActivityNode.0"/>
        <ownedActivityEdge source="//RbacPolicy/createSession/@activity/@ownedActivityNode.2" target="//RbacPolicy/createSession/@activity/@ownedActivityNode.1"/>
      </activity>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="permissions" upperBound="-1" eType="//Permission" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="-1" eType="//Role" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsdRelations" upperBound="-1" eType="//DsdRelation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="permssd" upperBound="-1" eType="//PermSsd" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="users" upperBound="-1" eType="//User" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ssdRelation" upperBound="-1" eType="//SsdRelation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Permission" eSuperTypes="//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="-1" eType="//Role" eOpposite="//Role/permissions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="object" lowerBound="1" eType="//Object" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" lowerBound="1" eType="//Operation" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
