/*
 * generated by Fujaba - CodeGen2
 */

package de.uni_kassel.fujaba.codegen;


import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import de.uni_kassel.fujaba.codegen.rules.CheckOperation;
import de.uni_kassel.fujaba.codegen.rules.ExecuteStoryPatternOperation;
import de.uni_kassel.fujaba.codegen.rules.ObjectAssignmentOperation;
import de.uni_kassel.fujaba.codegen.rules.Operation;
import de.uni_kassel.fujaba.codegen.rules.SearchOperation;
import de.uni_kassel.fujaba.codegen.rules.Token;
import de.uni_kassel.fujaba.codegen.rules.UMLObjectRef;
import de.uni_paderborn.fujaba.uml.behavior.UMLObject;
import de.upb.tools.sdm.JavaSDM;
import de.upb.tools.sdm.JavaSDMException; // requires Fujaba5/libs/RuntimeTools.jar in classpath


public class SequenceUtility
{

   public static boolean fujaba__success_used = false;
   
   public boolean getFujabaSuccessUsed()
   {
      return fujaba__success_used;
   }
   
   public boolean setFujabaSuccessUsed(boolean value)
   {
      fujaba__success_used = value;
      return value;
   }
   
   public boolean createsCheck (Token t ){
      
      return false;
      
   }

   
   public List getExecutionOrder (Token t ){
      boolean fujaba__Success = false;
      ArrayList order = null;

      // story pattern successor
      try 
      {
         fujaba__Success = false; 

         // create object
         order = new ArrayList ( );
         // collabStat call
         getExecutionOrder(t, order);
            fujaba__Success = true;
      }
      catch ( JavaSDMException fujaba__InternalException )
      {
         fujaba__Success = false;
      }

      return order;
      
   }

   
   private void getExecutionOrder (Token t , List order ){
      boolean fujaba__Success = false;
      Iterator fujaba__IterTToChild = null;
      Token child = null;

      // story pattern 
      try 
      {
         fujaba__Success = false; 

         // check object order is really bound
         JavaSDM.ensure ( order != null );
         // check object t is really bound
         JavaSDM.ensure ( t != null );
         // create link
         order.add (t);

            fujaba__Success = true;
      }
      catch ( JavaSDMException fujaba__InternalException )
      {
         fujaba__Success = false;
      }

      // story pattern storypatternwithparams
      try 
      {
         fujaba__Success = false; 

         // check object t is really bound
         JavaSDM.ensure ( t != null );
         // iterate to-many link children from t to child
         fujaba__Success = false;
         fujaba__IterTToChild = t.iteratorOfChildren ();
         while ( fujaba__IterTToChild.hasNext () )
         {
            try
            {
               child = (Token) fujaba__IterTToChild.next ();

               // check object child is really bound
               JavaSDM.ensure ( child != null );
               // check isomorphic binding between objects t and child
               JavaSDM.ensure ( !t.equals (child) );

               // collabStat call
               getExecutionOrder(child, order);
               
               fujaba__Success = true;
            }
            catch ( JavaSDMException fujaba__InternalException )
            {
               fujaba__Success = false;
            }
         }
         JavaSDM.ensure (fujaba__Success);
            fujaba__Success = true;
      }
      catch ( JavaSDMException fujaba__InternalException )
      {
         fujaba__Success = false;
      }

      return ;
      
   }

   public Operation getOperationToContinue (Token op){
      return getOperationToContinue (op, false);
   }
   
   public Operation getOperationToContinue (Token op, boolean returnNegative ){
      boolean fujaba__Success = false;
      Token parent = null;
      Object fujaba__TmpObject = null;
      SearchOperation search = null;
      UMLObject o = null;
      UMLObjectRef ref = null;
      ExecuteStoryPatternOperation pattern = null;

      // story pattern successor
      try 
      {
         fujaba__Success = false; 

         // check object op is really bound
         JavaSDM.ensure ( op != null );
         // bind object
         parent = op.getParent ();

         // check object parent is really bound
         JavaSDM.ensure ( parent != null );
         
         // check isomorphic binding between objects parent and op
         JavaSDM.ensure ( !parent.equals (op) );

         
         // collabStat call
         op = parent;
            fujaba__Success = true;
      }
      catch ( JavaSDMException fujaba__InternalException )
      {
         fujaba__Success = false;
      }

      if (fujaba__Success)
      {
         // story pattern 
         try 
         {
            fujaba__Success = false; 

            fujaba__TmpObject = op;

            // ensure correct type and really bound of object search
            JavaSDM.ensure ( fujaba__TmpObject instanceof SearchOperation );
            search = (SearchOperation) fujaba__TmpObject;

               fujaba__Success = true;
         }
         catch ( JavaSDMException fujaba__InternalException )
         {
            fujaba__Success = false;
         }

         if (fujaba__Success)
         {
            // story pattern storypatternwithparams
            try 
            {
               fujaba__Success = false; 

               // check object search is really bound
               JavaSDM.ensure ( search != null );
               // bind object
               ref = search.getSubject ();

               // check object ref is really bound
               JavaSDM.ensure ( ref != null );
               
               // bind object
               o = ref.getRef ();

               // check object o is really bound
               JavaSDM.ensure ( o != null );

               if (!(returnNegative && o.getType() == UMLObject.NEGATIVE && search.hasSingleResult()))
               {
               // constraint !search.hasSingleResult()
               JavaSDM.ensure ( !search.hasSingleResult() );
               }
               
               
                  fujaba__Success = true;
            }
            catch ( JavaSDMException fujaba__InternalException )
            {
               fujaba__Success = false;
            }

            if (fujaba__Success)
            {
               return search;
               
            }

         }
         else
         {
            // story pattern Successor of 
            try 
            {
               fujaba__Success = false; 

               fujaba__TmpObject = op;

               // ensure correct type and really bound of object pattern
               JavaSDM.ensure ( fujaba__TmpObject instanceof ExecuteStoryPatternOperation );
               pattern = (ExecuteStoryPatternOperation) fujaba__TmpObject;

                  fujaba__Success = true;
            }
            catch ( JavaSDMException fujaba__InternalException )
            {
               fujaba__Success = false;
            }

            if (fujaba__Success)
            {
               return pattern;
               
            }

         }
         return getOperationToContinue(op);
         
      }
      else
      {
         return null;
         
      }
      
   }

   
   public int getPatternDepth (Token t ){
      boolean fujaba__Success = false;
      Iterator fujaba__IterTToPattern = null;
      Object fujaba__TmpObject = null;
      ExecuteStoryPatternOperation pattern = null;

      int count=-1;
      // story pattern storypatternwithparams
      try 
      {
         fujaba__Success = false; 

         // check object t is really bound
         JavaSDM.ensure ( t != null );
         // iterate to-many link $link.InstanceOf.Name from t to pattern
         fujaba__Success = false;
         fujaba__IterTToPattern = new de.uni_kassel.sdm.Path (t, "parent*");
         while ( fujaba__IterTToPattern.hasNext () )
         {
            try
            {
               fujaba__TmpObject =  fujaba__IterTToPattern.next ();

               // ensure correct type and really bound of object pattern
               JavaSDM.ensure ( fujaba__TmpObject instanceof ExecuteStoryPatternOperation );
               pattern = (ExecuteStoryPatternOperation) fujaba__TmpObject;

               // check isomorphic binding between objects t and pattern
               // JavaSDM.ensure ( !t.equals (pattern) );

               // collabStat call
               count++;
               
               fujaba__Success = true;
            }
            catch ( JavaSDMException fujaba__InternalException )
            {
               fujaba__Success = false;
            }
         }
         JavaSDM.ensure (fujaba__Success);
            fujaba__Success = true;
      }
      catch ( JavaSDMException fujaba__InternalException )
      {
         fujaba__Success = false;
      }

      return count;
      
   }

   
   public SearchOperation getSearchOperation (Token op ){
      boolean fujaba__Success = false;
      Object fujaba__TmpObject = null;
      SearchOperation search = null;
      UMLObject o = null;
      UMLObjectRef ref = null;
      ExecuteStoryPatternOperation pattern = null;
      Token parent = null;

      // story pattern 
      try 
      {
         fujaba__Success = false; 

         fujaba__TmpObject = op;

         // ensure correct type and really bound of object search
         JavaSDM.ensure ( fujaba__TmpObject instanceof SearchOperation );
         search = (SearchOperation) fujaba__TmpObject;

         // bind object
         ref = search.getSubject ();

         // check object ref is really bound
         JavaSDM.ensure ( ref != null );
         
         // bind object
         o = ref.getRef ();

         // check object o is really bound
         JavaSDM.ensure ( o != null );
         
         
         
            fujaba__Success = true;
      }
      catch ( JavaSDMException fujaba__InternalException )
      {
         fujaba__Success = false;
      }

      if (fujaba__Success)
      {
         return search;
         
      }
      else
      {
         // story pattern Successor of 
         try 
         {
            fujaba__Success = false; 

            fujaba__TmpObject = op;

            // ensure correct type and really bound of object pattern
            JavaSDM.ensure ( fujaba__TmpObject instanceof ExecuteStoryPatternOperation );
            pattern = (ExecuteStoryPatternOperation) fujaba__TmpObject;

               fujaba__Success = true;
         }
         catch ( JavaSDMException fujaba__InternalException )
         {
            fujaba__Success = false;
         }

         if (fujaba__Success)
         {
            return null;
            
         }
         else
         {
            // story pattern successor
            try 
            {
               fujaba__Success = false; 

               // check object op is really bound
               JavaSDM.ensure ( op != null );
               // bind object
               parent = op.getParent ();

               // check object parent is really bound
               JavaSDM.ensure ( parent != null );
               
               // check isomorphic binding between objects parent and op
               JavaSDM.ensure ( !parent.equals (op) );

               
                  fujaba__Success = true;
            }
            catch ( JavaSDMException fujaba__InternalException )
            {
               fujaba__Success = false;
            }

            if (fujaba__Success)
            {
               return getSearchOperation(parent);
               
            }
            else
            {
               return null;
               
            }

         }

      }
      
   }

   
   public UMLObject getSearchToContinue (Token op ){
      boolean fujaba__Success = false;
      Object fujaba__TmpObject = null;
      SearchOperation search = null;
      UMLObject o = null;
      UMLObjectRef ref = null;

      // story pattern successor
      try 
      {
         fujaba__Success = false; 

         fujaba__TmpObject = getOperationToContinue(op);

         // ensure correct type and really bound of object search
         JavaSDM.ensure ( fujaba__TmpObject instanceof SearchOperation );
         search = (SearchOperation) fujaba__TmpObject;

         // bind object
         ref = search.getSubject ();

         // check object ref is really bound
         JavaSDM.ensure ( ref != null );
         
         // bind object
         o = ref.getRef ();

         // check object o is really bound
         JavaSDM.ensure ( o != null );
         
         
         
            fujaba__Success = true;
      }
      catch ( JavaSDMException fujaba__InternalException )
      {
         fujaba__Success = false;
      }

      if (fujaba__Success)
      {
         return o;
         
      }
      else
      {
         return null;
         
      }
      
   }

   
   public UMLObject getSearch (Token op ){
      boolean fujaba__Success = false;
      SearchOperation searchOp = null;
      UMLObject o = null;
      UMLObjectRef ref = null;

      // story pattern successor
      try 
      {
         fujaba__Success = false; 

         searchOp = getSearchOperation(op);

         // check object searchOp is really bound
         JavaSDM.ensure ( searchOp != null );
         // bind object
         ref = searchOp.getSubject ();

         // check object ref is really bound
         JavaSDM.ensure ( ref != null );
         
         // bind object
         o = ref.getRef ();

         // check object o is really bound
         JavaSDM.ensure ( o != null );
         
         
         
            fujaba__Success = true;
      }
      catch ( JavaSDMException fujaba__InternalException )
      {
         fujaba__Success = false;
      }

      if (fujaba__Success)
      {
         return o;
         
      }
      else
      {
         return null;
         
      }
      
   }

   
   public boolean hasCheck (Token t ){
      boolean fujaba__Success = false;
      Object fujaba__TmpObject = null;
      CheckOperation check = null;
      ObjectAssignmentOperation assign = null;

      // story pattern successor
      try 
      {
         fujaba__Success = false; 

         fujaba__TmpObject = t;

         // ensure correct type and really bound of object check
         JavaSDM.ensure ( fujaba__TmpObject instanceof CheckOperation );
         check = (CheckOperation) fujaba__TmpObject;

            fujaba__Success = true;
      }
      catch ( JavaSDMException fujaba__InternalException )
      {
         fujaba__Success = false;
      }

      if (fujaba__Success)
      {
         return true;
         
      }
      else
      {
         // story pattern storypatternwithparams
         try 
         {
            fujaba__Success = false; 

            fujaba__TmpObject = t;

            // ensure correct type and really bound of object assign
            JavaSDM.ensure ( fujaba__TmpObject instanceof ObjectAssignmentOperation );
            assign = (ObjectAssignmentOperation) fujaba__TmpObject;

               fujaba__Success = true;
         }
         catch ( JavaSDMException fujaba__InternalException )
         {
            fujaba__Success = false;
         }

         if (fujaba__Success)
         {
            return true;
            
         }
         else
         {
            return false;
            
         }

      }
      
   }

   
   public boolean hasFirstCheck (Token t ){
      boolean fujaba__Success = false;
      Operation cont = null;
      List order = null;
      int index = 0;
      Iterator fujaba__IterOrderToBefore = null;
      Object fujaba__TmpObject = null;
      Token before = null;

      // story pattern 
      try 
      {
         fujaba__Success = false; 

         // check object t is really bound
         JavaSDM.ensure ( t != null );
         // constraint hasCheck(t)
         JavaSDM.ensure ( hasCheck(t) );
            fujaba__Success = true;
      }
      catch ( JavaSDMException fujaba__InternalException )
      {
         fujaba__Success = false;
      }

      if (fujaba__Success)
      {
         // story pattern storypatternwithparams
         try 
         {
            fujaba__Success = false; 

            
            cont = getOperationToContinue(t, true);

            // check object cont is really bound
            JavaSDM.ensure ( cont != null );
            // create object
            order = getExecutionOrder(cont);
               fujaba__Success = true;
         }
         catch ( JavaSDMException fujaba__InternalException )
         {
            fujaba__Success = false;
         }

         if (fujaba__Success)
         {
            // story pattern 
            try 
            {
               fujaba__Success = false; 

               // check object order is really bound
               JavaSDM.ensure ( order != null );
               // check object t is really bound
               JavaSDM.ensure ( t != null );
               // check link contains from order to t
               JavaSDM.ensure (order.contains (t));

               // collabStat call
               index = order.indexOf(t);
                  fujaba__Success = true;
            }
            catch ( JavaSDMException fujaba__InternalException )
            {
               fujaba__Success = false;
            }

            if (fujaba__Success)
            {
               // story pattern Successor of 
               try 
               {
                  fujaba__Success = false; 
                  
                  // just look at the previous operation 
                  index = index -1;
                  if (index <= 0)
                  {
                     // yes, I am the first
                     return true;
                  }
                  before = (Token) order.get(index);
                  
                  // well, if there is no surrounding block and the previous operation is a search,
                  // then the previous operation is a search 
                  boolean tmp = (before instanceof SearchOperation);
                  tmp = tmp && ! this.needsStoryBlock(t);
                  //  System.out.println("tmp: " + tmp);
                  
                  // or if it actually is a check
                  tmp = tmp || hasCheck(before);
                  tmp = tmp && getOperationToContinue(before, true) == cont;
                  JavaSDM.ensure(tmp);
                   
//                  // check object order is really bound
//                  JavaSDM.ensure ( order != null );
//                  // iterate to-many link contains from order to before
//                  fujaba__Success = false;
//                  fujaba__IterOrderToBefore = order.iterator ();
//                  while ( !(fujaba__Success) && fujaba__IterOrderToBefore.hasNext () )
//                  {
//                     try
//                     {
//                        fujaba__TmpObject =  fujaba__IterOrderToBefore.next ();
//
//                        // ensure correct type and really bound of object before
//                        JavaSDM.ensure ( fujaba__TmpObject instanceof Token );
//                        before = (Token) fujaba__TmpObject;
//
//                        // constraint hasCheck(before)
//                        JavaSDM.ensure ( hasCheck(before) );
//                        // constraint index > order.indexOf(before)
//                        JavaSDM.ensure ( index > order.indexOf(before) );
//                        
//                        fujaba__Success = true;
//                     }
//                     catch ( JavaSDMException fujaba__InternalException )
//                     {
//                        fujaba__Success = false;
//                     }
//                  }
//                  JavaSDM.ensure (fujaba__Success);
                     fujaba__Success = true;
               }
               catch ( JavaSDMException fujaba__InternalException )
               {
                  fujaba__Success = false;
               }

               if (fujaba__Success)
               {
                  return false;
                  
               }
               else
               {
                  return true;
                  
               }

            }
            else
            {
               return false;
               
            }

         }
         else
         {
            return false;
            
         }

      }
      else
      {
         return false;
         
      }
      
   }

   
   public boolean hasLastCheck (Token t ){
      boolean fujaba__Success = false;
      Operation cont = null;
      List order = null;
      int index = 0;
      Object fujaba__TmpObject = null;
      Token after = null;

      // story pattern storypatternwithparams
      try 
      {
         fujaba__Success = false; 

         // check object t is really bound 
         JavaSDM.ensure ( t != null );
         // constraint hasCheck(t)
         JavaSDM.ensure ( hasCheck(t) );
            fujaba__Success = true;
      }
      catch ( JavaSDMException fujaba__InternalException )
      {
         fujaba__Success = false;
      }

      if (fujaba__Success)
      {
         // story pattern Successor of storypatternwithparams
         try 
         {
            fujaba__Success = false; 

            cont = getOperationToContinue(t, true);

            // check object cont is really bound
            JavaSDM.ensure ( cont != null );
            // create object
            order = getExecutionOrder(cont);
               fujaba__Success = true;
         }
         catch ( JavaSDMException fujaba__InternalException )
         {
            fujaba__Success = false;
         }

         if (fujaba__Success)
         {
            // story pattern Successor of Successor of storypatternwithparams
            try 
            {
               fujaba__Success = false; 

               // check object order is really bound
               JavaSDM.ensure ( order != null );
               // check object t is really bound
               JavaSDM.ensure ( t != null );
               // check link contains from order to t
               JavaSDM.ensure (order.contains (t));

               // collabStat call
               index = order.indexOf(t);
                  fujaba__Success = true;
            }
            catch ( JavaSDMException fujaba__InternalException )
            {
               fujaba__Success = false;
            }

            if (fujaba__Success)
            {
               if (index+1 < order.size())
               {
                  // story pattern 
                  try 
                  {
                     fujaba__Success = false; 

                     // check object order is really bound
                     JavaSDM.ensure ( order != null );
                     // bind object
                     fujaba__TmpObject = order.get (index+1);

                     // ensure correct type and really bound of object after
                     JavaSDM.ensure ( fujaba__TmpObject instanceof Token );
                     after = (Token) fujaba__TmpObject;

                     
                     
                        fujaba__Success = true;
                  }
                  catch ( JavaSDMException fujaba__InternalException )
                  {
                     fujaba__Success = false;
                  }

                  if (fujaba__Success)
                  {
                     if (hasCheck(after))
                     {
                        return false;
                        
                     }
                     else
                     {
                        return true;
                        
                     }

                  }
                  else
                  {
                     return true;
                     
                  }

               }
               else
               {
                  return true;
                  
               }

            }
            else
            {
               return true;
               
            }

         }
         else
         {
            return true;
            
         }

      }
      else
      {
         return false;
         
      }
      
   }

   
   public boolean needsStoryBlock (ExecuteStoryPatternOperation pattern ){
      boolean fujaba__Success = false;
      Iterator fujaba__IterPatternToChild1 = null;
      Token child1 = null;
      Iterator fujaba__IterPatternToChild2 = null;
      Token child2 = null;

      // story pattern storypatternwithparams
      try 
      {
         fujaba__Success = false; 

         // check object pattern is really bound
         JavaSDM.ensure ( pattern != null );
         // iterate to-many link children from pattern to child1
         fujaba__Success = false;
         fujaba__IterPatternToChild1 = pattern.iteratorOfChildren ();
         while ( !(fujaba__Success) && fujaba__IterPatternToChild1.hasNext () )
         {
            try
            {
               child1 = (Token) fujaba__IterPatternToChild1.next ();

               // check object child1 is really bound
               JavaSDM.ensure ( child1 != null );
               // check isomorphic binding between objects pattern and child1
               JavaSDM.ensure ( !pattern.equals (child1) );

               
               fujaba__Success = true;
            }
            catch ( JavaSDMException fujaba__InternalException )
            {
               fujaba__Success = false;
            }
         }
         JavaSDM.ensure (fujaba__Success);
            fujaba__Success = true;
      }
      catch ( JavaSDMException fujaba__InternalException )
      {
         fujaba__Success = false;
      }

      if (fujaba__Success)
      {
         // story pattern Successor of storypatternwithparams
         try 
         {
            fujaba__Success = false; 

            // check object child1 is really bound
            JavaSDM.ensure ( child1 != null );
            // check object pattern is really bound
            JavaSDM.ensure ( pattern != null );
            // check isomorphic binding between objects pattern and child1
            JavaSDM.ensure ( !pattern.equals (child1) );

            // check link children from child1 to pattern
            JavaSDM.ensure (pattern.equals (child1.getParent ()));

            // iterate to-many link children from pattern to child2
            fujaba__Success = false;
            fujaba__IterPatternToChild2 = pattern.iteratorOfChildren ();
            while ( !(fujaba__Success) && fujaba__IterPatternToChild2.hasNext () )
            {
               try
               {
                  child2 = (Token) fujaba__IterPatternToChild2.next ();

                  // check object child2 is really bound
                  JavaSDM.ensure ( child2 != null );
                  // check isomorphic binding between objects child2 and child1
                  JavaSDM.ensure ( !child2.equals (child1) );

                  // check isomorphic binding between objects pattern and child2
                  JavaSDM.ensure ( !pattern.equals (child2) );

                  
                  fujaba__Success = true;
               }
               catch ( JavaSDMException fujaba__InternalException )
               {
                  fujaba__Success = false;
               }
            }
            JavaSDM.ensure (fujaba__Success);
               fujaba__Success = true;
         }
         catch ( JavaSDMException fujaba__InternalException )
         {
            fujaba__Success = false;
         }

         if (fujaba__Success)
         {
            return true;
            
         }
         else
         {
            return child1.sizeOfChildren() > 0;
            
         }

      }
      else
      {
         return false;
         
      }
      
   }

   
   public boolean needsStoryBlock (Token t ){
      boolean fujaba__Success = false;
      Iterator fujaba__IterTToPattern = null;
      Object fujaba__TmpObject = null;
      ExecuteStoryPatternOperation pattern = null;

      // story pattern storypatternwithparams
      try 
      {
         fujaba__Success = false; 

         // check object t is really bound
         JavaSDM.ensure ( t != null );
         // iterate to-many link $link.InstanceOf.Name from t to pattern
         fujaba__Success = false;
         fujaba__IterTToPattern = new de.uni_kassel.sdm.Path (t, "parent*");
         while ( !(fujaba__Success) && fujaba__IterTToPattern.hasNext () )
         {
            try
            {
               fujaba__TmpObject =  fujaba__IterTToPattern.next ();

               // ensure correct type and really bound of object pattern
               JavaSDM.ensure ( fujaba__TmpObject instanceof ExecuteStoryPatternOperation );
               pattern = (ExecuteStoryPatternOperation) fujaba__TmpObject;

               // check isomorphic binding between objects t and pattern
               JavaSDM.ensure ( !t.equals (pattern) );

               
               fujaba__Success = true;
            }
            catch ( JavaSDMException fujaba__InternalException )
            {
               fujaba__Success = false;
            }
         }
         JavaSDM.ensure (fujaba__Success);
            fujaba__Success = true;
      }
      catch ( JavaSDMException fujaba__InternalException )
      {
         fujaba__Success = false;
      }

      if (fujaba__Success)
      {
         return needsStoryBlock(pattern);
         
      }
      else
      {
         return true;
         
      }
      
   }

   
   public void removeYou()
   {
   }
}


