<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ecoreutils" nsURI="platform:/plugin/org.moflon.core.ecoreutils/model/Ecoreutils.ecore" nsPrefix="org.moflon.core.ecoreutils">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="basePackage" value="org.moflon.core"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="ECharContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EChar"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EStringContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EBigIntegerContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MoflonListItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="next" eType="//MoflonListItem" eOpposite="//MoflonListItem/previous"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="previous" eType="//MoflonListItem" eOpposite="//MoflonListItem/next"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MoflonList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1" eType="//MoflonListItem" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EDoubleContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EShortContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EByteContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EByte"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EFloatContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELongContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EIntContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EBooleanContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EDateContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
