/*
 * generated by Xtext 2.10.0
 */
package org.moflon.gt.mosl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MOSLGTStandaloneSetup extends MOSLGTStandaloneSetupGenerated {

	def static void doSetup() {
		new MOSLGTStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
