<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mnoq" nsURI="platform:/plugin/org.moflon.maave.tests.lang.mnoq/model/Mnoq.ecore" nsPrefix="org.moflon.maave.tests.lang.mnoq">
  <eClassifiers xsi:type="ecore:EClass" name="O"/>
  <eClassifiers xsi:type="ecore:EClass" name="Q">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ns" upperBound="-1" eType="//N" eOpposite="//N/qs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="N">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mms" upperBound="-1" eType="//M" eOpposite="//M/nns"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="qs" upperBound="-1" eType="//Q" eOpposite="//Q/ns"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="M">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nns" upperBound="-1" eType="//N" eOpposite="//N/mms"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="o" eType="//O"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
