<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="language" nsURI="platform:/plugin/org.moflon.ide.visualization.dot.language/model/Language.ecore"
    nsPrefix="org.moflon.ide.visualization.dot.language">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="basePackage" value="org.moflon.ide.visualization.dot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="NodeCommand" abstract="true" eSuperTypes="#//AbstractNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fillcolor" ordered="false"
        lowerBound="1" eType="#//DotColor" defaultValueLiteral="WHITE"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" ordered="false"
        lowerBound="1" eType="#//DotColor" defaultValueLiteral="BLACK"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bold" ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RecordEntry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="record" eType="#//Record"
        eOpposite="#//Record/entries"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DInheritance" eSuperTypes="#//EdgeCommand"/>
  <eClassifiers xsi:type="ecore:EClass" name="Box" eSuperTypes="#//NodeCommand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="href" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoubleCircle" eSuperTypes="#//NodeCommand"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractSubGraph" abstract="true" eSuperTypes="#//AbstractGraph">
    <eStructuralFeatures xsi:type="ecore:EReference" name="containingGraph" eType="#//AbstractGraph"
        eOpposite="#//AbstractGraph/subGraphs"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cluster" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubGraph" eSuperTypes="#//AbstractSubGraph #//DirectedGraph"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DotColor">
    <eLiterals name="BLACK" literal="BLACK"/>
    <eLiterals name="WHITE" value="6" literal="WHITE"/>
    <eLiterals name="LIGHTYELLOW" value="4" literal="LIGHTYELLOW"/>
    <eLiterals name="MISTYROSE" value="5" literal="MISTYROSE"/>
    <eLiterals name="GREEN" value="1" literal="GREEN"/>
    <eLiterals name="BLUE" value="2" literal="BLUE"/>
    <eLiterals name="RED" value="3" literal="RED"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DirectedGraph" eSuperTypes="#//AbstractGraph">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entries" upperBound="-1"
        eType="#//LabelEntry" containment="true" eOpposite="#//LabelEntry/directedGraph"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Record" eSuperTypes="#//NodeCommand">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entries" upperBound="-1"
        eType="#//RecordEntry" containment="true" eOpposite="#//RecordEntry/record"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rounded" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Taper" eSuperTypes="#//EdgeCommand"/>
  <eClassifiers xsi:type="ecore:EClass" name="Point" eSuperTypes="#//NodeCommand"/>
  <eClassifiers xsi:type="ecore:EClass" name="LabelEntry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="directedGraph" eType="#//DirectedGraph"
        eOpposite="#//DirectedGraph/entries"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DComposite" eSuperTypes="#//EdgeCommand"/>
  <eClassifiers xsi:type="ecore:EClass" name="EdgeCommand" eSuperTypes="#//AbstractEdge">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" ordered="false"
        lowerBound="1" eType="#//DotColor" defaultValueLiteral="BLACK"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="constrained" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractGraph" abstract="true" eSuperTypes="platform:/plugin/MocaTree/model/MocaTree.ecore#//Node">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//AbstractNode" containment="true" eOpposite="#//AbstractNode/graph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edges" upperBound="-1"
        eType="#//AbstractEdge" containment="true" eOpposite="#//AbstractEdge/graph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subGraphs" upperBound="-1"
        eType="#//AbstractSubGraph" containment="true" eOpposite="#//AbstractSubGraph/containingGraph"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractNode" abstract="true" eSuperTypes="#//LabeledGraphObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="graph" eType="#//AbstractGraph"
        eOpposite="#//AbstractGraph/nodes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractEdge" abstract="true" eSuperTypes="#//LabeledGraphObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="graph" eType="#//AbstractGraph"
        eOpposite="#//AbstractGraph/edges"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//AbstractNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//AbstractNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LabeledGraphObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractSkinParam" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="#//DotColor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ClassSkinParamValues">
    <eLiterals name="classArrowColor" literal="CLASS_ARROW_COLOR"/>
    <eLiterals name="classBackgroundColor" value="1" literal="CLASS_BACKGROUND_COLOR"/>
    <eLiterals name="classBorderColor" value="2" literal="CLASS_BORDER_COLOR"/>
    <eLiterals name="packageBackgroundColor" value="3" literal="PACKAGE_BACKGROUND_COLOR"/>
    <eLiterals name="packageBorderColor" value="4" literal="PACKAGE_BORDER_COLOR"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassSkinParam" eSuperTypes="#//AbstractSkinParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//ClassSkinParamValues"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassSkinParamFont" eSuperTypes="#//ClassSkinParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="style" eType="#//SkinParamStyles"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassGraph" eSuperTypes="#//AbstractGraph">
    <eStructuralFeatures xsi:type="ecore:EReference" name="skinparams" upperBound="-1"
        eType="#//ClassSkinParam" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="packages" upperBound="-1"
        eType="#//PPackage" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubClassGraph" eSuperTypes="#//AbstractSubGraph #//ClassGraph"/>
  <eClassifiers xsi:type="ecore:EClass" name="PClass" eSuperTypes="#//PNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//PAttribute" containment="true" eOpposite="#//PAttribute/belongingClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="methods" upperBound="-1"
        eType="#//PMethod" containment="true" eOpposite="#//PMethod/belongingClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PAbstract" eSuperTypes="#//PClass"/>
  <eClassifiers xsi:type="ecore:EClass" name="PEnum" eSuperTypes="#//PNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="literals" upperBound="-1"
        eType="#//PEnumLiteral" containment="true" eOpposite="#//PEnumLiteral/belongingEnumeration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PEnumLiteral">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="belongingEnumeration" eType="#//PEnum"
        eOpposite="#//PEnum/literals"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PDataType" eSuperTypes="#//PNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="PAssociation" eSuperTypes="#//PEdge">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oppositeLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="srcMultiplicity" eType="#//PMultiplicity"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trgMultiplicity" lowerBound="1"
        eType="#//PMultiplicity" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PComposite" eSuperTypes="#//PAssociation"/>
  <eClassifiers xsi:type="ecore:EClass" name="PInheritance" eSuperTypes="#//PEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="PEdge" abstract="true" eSuperTypes="#//AbstractEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="PMultiplicity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PNode" abstract="true" eSuperTypes="#//AbstractNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="PPackage" eSuperTypes="#//LabeledGraphObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classes" upperBound="-1"
        eType="#//PClass" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PInterface" eSuperTypes="#//PClass"/>
  <eClassifiers xsi:type="ecore:EClass" name="PAttribute" eSuperTypes="#//PNamedObject #//PVisibilityObject #//PTypedObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="belongingClass" eType="#//PClass"
        eOpposite="#//PClass/attributes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PMethod" eSuperTypes="#//PNamedObject #//PTypedObject #//PVisibilityObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="belongingClass" eType="#//PClass"
        eOpposite="#//PClass/methods"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//PParameter" containment="true" eOpposite="#//PParameter/method"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PParameter" eSuperTypes="#//PTypedObject #//PNamedObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="method" eType="#//PMethod"
        eOpposite="#//PMethod/parameters"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PVisibilty">
    <eLiterals name="PRIVATE_VIEW" literal="PRIVATE_VIEW"/>
    <eLiterals name="PUBLIC_VIEW" value="1" literal="PUBLIC_VIEW"/>
    <eLiterals name="PROTECTED_VIEW" value="2" literal="PROTECTED_VIEW"/>
    <eLiterals name="PACKAGE_ONLY" value="3" literal="PACKAGE_ONLY"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PNamedObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PVisibilityObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibilty" eType="#//PVisibilty"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sign" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PTypedObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SkinParamStyles">
    <eLiterals name="PLAIN" literal="plain"/>
    <eLiterals name="BOLD" value="1" literal="bold"/>
    <eLiterals name="ITALIC" value="2" literal="italic"/>
  </eClassifiers>
</ecore:EPackage>
