<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:activities="platform:/plugin/SDMLanguage/model/SDMLanguage.ecore#//activities" xmlns:callExpressions="platform:/plugin/SDMLanguage/model/SDMLanguage.ecore#//calls/callExpressions" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:expressions="platform:/plugin/SDMLanguage/model/SDMLanguage.ecore#//expressions" xmlns:patternExpressions="platform:/plugin/SDMLanguage/model/SDMLanguage.ecore#//patterns/patternExpressions" name="org.moflon.sdm.constraints.scopevalidation" nsURI="platform:/plugin/org.moflon.sdm.constraints.scopevalidation/model/Scopevalidation.ecore" nsPrefix="org.moflon.sdm.constraints.scopevalidation">
  <eClassifiers xsi:type="ecore:EClass" name="AttributeConstraintBlackPatternInvocationBuilder">
    <eSuperTypes href="platform:/plugin/ScopeValidation/model/ScopeValidation.ecore#//BlackPatternBuilder"/>
    <eOperations xsi:type="activities:MoflonEOperation" name="analyzeDependencies">
      <eParameters name="patternInvocationBuilder">
        <eType xsi:type="ecore:EClass" href="platform:/plugin/ScopeValidation/model/ScopeValidation.ecore#//PatternInvocationBuilder"/>
      </eParameters>
      <eParameters name="storyPattern">
        <eType xsi:type="ecore:EClass" href="platform:/plugin/SDMLanguage/model/SDMLanguage.ecore#//patterns/StoryPattern"/>
      </eParameters>
      <eParameters name="pattern">
        <eType xsi:type="ecore:EClass" href="http://gervarro.org/democles/specification.ecore#//Pattern"/>
      </eParameters>
      <activity owningOperation="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies">
        <ownedActivityNode xsi:type="activities:StoryNode" name="ActivityNode2" comment="ActivityNode2" outgoing="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityEdge.0 //AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityEdge.1" incoming="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityEdge.4">
          <storyPattern comment="ActivityNode2">
            <objectVariable name="variableType" incomingLink="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.3 //AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.4">
              <type xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EDataType"/>
            </objectVariable>
            <objectVariable name="pattern" outgoingLink="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.0 //AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.1" bindingState="BOUND">
              <type xsi:type="ecore:EClass" href="http://gervarro.org/democles/specification.ecore#//Pattern"/>
            </objectVariable>
            <objectVariable name="primitiveVariable" incomingLink="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.2" outgoingLink="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.3">
              <type xsi:type="ecore:EClass" href="platform:/plugin/SDMLanguage/model/SDMLanguage.ecore#//patterns/AttributeConstraints/PrimitiveVariable"/>
            </objectVariable>
            <objectVariable name="assignmentConstraint" outgoingLink="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.2" bindingState="BOUND">
              <type xsi:type="ecore:EClass" href="platform:/plugin/SDMLanguage/model/SDMLanguage.ecore#//patterns/AttributeConstraints/AssignmentConstraint"/>
            </objectVariable>
            <objectVariable name="newVariable" incomingLink="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.0" outgoingLink="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.4" bindingOperator="CREATE">
              <type xsi:type="ecore:EClass" href="http://gervarro.org/democles/constraint/emf.ecore#//EMFVariable"/>
              <attributeAssignment>
                <attribute href="http://gervarro.org/democles/specification.ecore#//Variable/name"/>
                <valueExpression xsi:type="patternExpressions:AttributeValueExpression" object="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.2">
                  <attribute href="platform:/plugin/SDMLanguage/model/SDMLanguage.ecore#//patterns/AttributeConstraints/AttributeConstraintVariable/name"/>
                </valueExpression>
              </attributeAssignment>
            </objectVariable>
            <objectVariable name="existingVariable" incomingLink="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.1" bindingSemantics="NEGATIVE">
              <type xsi:type="ecore:EClass" href="http://gervarro.org/democles/constraint/emf.ecore#//EMFVariable"/>
              <constraint>
                <constraintExpression xsi:type="expressions:ComparisonExpression" operator="EQUAL">
                  <rightExpression xsi:type="patternExpressions:AttributeValueExpression" object="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.2">
                    <attribute href="platform:/plugin/SDMLanguage/model/SDMLanguage.ecore#//patterns/AttributeConstraints/AttributeConstraintVariable/name"/>
                  </rightExpression>
                  <leftExpression xsi:type="patternExpressions:AttributeValueExpression" object="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.5">
                    <attribute href="http://gervarro.org/democles/specification.ecore#//Variable/name"/>
                  </leftExpression>
                </constraintExpression>
              </constraint>
            </objectVariable>
            <linkVariable name="symbolicParameters" target="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.4" source="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.1" bindingOperator="CREATE">
              <type href="http://gervarro.org/democles/specification.ecore#//Pattern/symbolicParameters"/>
            </linkVariable>
            <linkVariable name="symbolicParameters" target="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.5" source="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.1">
              <type href="http://gervarro.org/democles/specification.ecore#//Pattern/symbolicParameters"/>
            </linkVariable>
            <linkVariable name="parameter" target="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.2" source="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.3">
              <type href="platform:/plugin/SDMLanguage/model/SDMLanguage.ecore#//patterns/AttributeConstraints/AttributeValueConstraint/parameter"/>
            </linkVariable>
            <linkVariable name="type" target="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.0" source="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.2">
              <type href="platform:/plugin/SDMLanguage/model/SDMLanguage.ecore#//patterns/AttributeConstraints/AttributeConstraintVariable/type"/>
            </linkVariable>
            <linkVariable name="eClassifier" target="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.0" source="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.4" bindingOperator="CREATE">
              <type href="http://gervarro.org/democles/constraint/emf.ecore#//EMFVariable/eClassifier"/>
            </linkVariable>
          </storyPattern>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StatementNode" name="ActivityNode5" outgoing="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityEdge.2" incoming="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityEdge.6">
          <statementExpression xsi:type="callExpressions:MethodCallExpression" callee="//AttributeConstraintBlackPatternInvocationBuilder/callSuperAnalyzeDependencies">
            <ownedParameterBindings parameter="//AttributeConstraintBlackPatternInvocationBuilder/callSuperAnalyzeDependencies/patternInvocationBuilder">
              <valueExpression xsi:type="callExpressions:ParameterExpression" parameter="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/patternInvocationBuilder"/>
            </ownedParameterBindings>
            <ownedParameterBindings parameter="//AttributeConstraintBlackPatternInvocationBuilder/callSuperAnalyzeDependencies/storyPattern">
              <valueExpression xsi:type="callExpressions:ParameterExpression" parameter="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/storyPattern"/>
            </ownedParameterBindings>
            <ownedParameterBindings parameter="//AttributeConstraintBlackPatternInvocationBuilder/callSuperAnalyzeDependencies/pattern">
              <valueExpression xsi:type="callExpressions:ParameterExpression" parameter="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/pattern"/>
            </ownedParameterBindings>
            <target xsi:type="patternExpressions:ObjectVariableExpression" object="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityNode.5/@storyPattern/@objectVariable.0"/>
          </statementExpression>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StopNode" incoming="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityEdge.3"/>
        <ownedActivityNode xsi:type="activities:StoryNode" name="ActivityNode1" comment="ActivityNode1" outgoing="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityEdge.3 //AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityEdge.4" incoming="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityEdge.0 //AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityEdge.2 //AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityEdge.7" forEach="true">
          <storyPattern comment="ActivityNode1">
            <objectVariable name="assignmentConstraint" incomingLink="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityNode.3/@storyPattern/@linkVariable.0">
              <type xsi:type="ecore:EClass" href="platform:/plugin/SDMLanguage/model/SDMLanguage.ecore#//patterns/AttributeConstraints/AssignmentConstraint"/>
            </objectVariable>
            <objectVariable name="storyPattern" outgoingLink="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityNode.3/@storyPattern/@linkVariable.0" bindingState="BOUND">
              <type xsi:type="ecore:EClass" href="platform:/plugin/SDMLanguage/model/SDMLanguage.ecore#//patterns/StoryPattern"/>
            </objectVariable>
            <linkVariable name="constraints" target="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityNode.3/@storyPattern/@objectVariable.0" source="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityNode.3/@storyPattern/@objectVariable.1">
              <type href="platform:/plugin/SDMLanguage/model/SDMLanguage.ecore#//patterns/StoryPattern/constraints"/>
            </linkVariable>
          </storyPattern>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StartNode" outgoing="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityEdge.5"/>
        <ownedActivityNode xsi:type="activities:StoryNode" name="ActivityNode4" comment="ActivityNode4" outgoing="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityEdge.6" incoming="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityEdge.5">
          <storyPattern comment="ActivityNode4">
            <objectVariable type="//AttributeConstraintBlackPatternInvocationBuilder" name="this" bindingState="BOUND"/>
          </storyPattern>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StatementNode" name="ActivityNode9" outgoing="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityEdge.7" incoming="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityEdge.1">
          <statementExpression xsi:type="callExpressions:MethodCallExpression" callee="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference">
            <ownedParameterBindings parameter="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/variable">
              <valueExpression xsi:type="patternExpressions:ObjectVariableExpression" object="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.4"/>
            </ownedParameterBindings>
            <ownedParameterBindings parameter="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/variableType">
              <valueExpression xsi:type="patternExpressions:ObjectVariableExpression" object="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.0"/>
            </ownedParameterBindings>
            <target xsi:type="patternExpressions:ObjectVariableExpression" object="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityNode.5/@storyPattern/@objectVariable.0"/>
          </statementExpression>
        </ownedActivityNode>
        <ownedActivityEdge source="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityNode.0" target="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityNode.3" guard="FAILURE"/>
        <ownedActivityEdge source="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityNode.0" target="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityNode.6" guard="SUCCESS"/>
        <ownedActivityEdge source="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityNode.1" target="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityNode.3"/>
        <ownedActivityEdge source="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityNode.3" target="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityNode.2" guard="END"/>
        <ownedActivityEdge source="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityNode.3" target="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityNode.0" guard="EACH_TIME"/>
        <ownedActivityEdge source="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityNode.4" target="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityNode.5"/>
        <ownedActivityEdge source="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityNode.5" target="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityNode.1"/>
        <ownedActivityEdge source="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityNode.6" target="//AttributeConstraintBlackPatternInvocationBuilder/analyzeDependencies/@activity/@ownedActivityNode.3"/>
      </activity>
    </eOperations>
    <eOperations xsi:type="activities:MoflonEOperation" name="callSuperAnalyzeDependencies">
      <eParameters name="patternInvocationBuilder">
        <eType xsi:type="ecore:EClass" href="platform:/plugin/ScopeValidation/model/ScopeValidation.ecore#//PatternInvocationBuilder"/>
      </eParameters>
      <eParameters name="storyPattern">
        <eType xsi:type="ecore:EClass" href="platform:/plugin/SDMLanguage/model/SDMLanguage.ecore#//patterns/StoryPattern"/>
      </eParameters>
      <eParameters name="pattern">
        <eType xsi:type="ecore:EClass" href="http://gervarro.org/democles/specification.ecore#//Pattern"/>
      </eParameters>
    </eOperations>
    <eOperations xsi:type="activities:MoflonEOperation" name="concat">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="param1">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eParameters>
      <eParameters name="param2">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eParameters>
    </eOperations>
    <eOperations xsi:type="activities:MoflonEOperation" name="calcLocalVariableName">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="variable">
        <eType xsi:type="ecore:EClass" href="http://gervarro.org/democles/specification.ecore#//Variable"/>
      </eParameters>
      <activity owningOperation="//AttributeConstraintBlackPatternInvocationBuilder/calcLocalVariableName">
        <ownedActivityNode xsi:type="activities:StartNode" outgoing="//AttributeConstraintBlackPatternInvocationBuilder/calcLocalVariableName/@activity/@ownedActivityEdge.0"/>
        <ownedActivityNode xsi:type="activities:StoryNode" name="ActivityNode6" comment="ActivityNode6" outgoing="//AttributeConstraintBlackPatternInvocationBuilder/calcLocalVariableName/@activity/@ownedActivityEdge.1" incoming="//AttributeConstraintBlackPatternInvocationBuilder/calcLocalVariableName/@activity/@ownedActivityEdge.2">
          <storyPattern comment="ActivityNode6">
            <objectVariable name="action" incomingLink="//AttributeConstraintBlackPatternInvocationBuilder/calcLocalVariableName/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.1 //AttributeConstraintBlackPatternInvocationBuilder/calcLocalVariableName/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.0">
              <type xsi:type="ecore:EClass" href="platform:/plugin/ControlFlow/model/ControlFlow.ecore#//Action"/>
            </objectVariable>
            <objectVariable name="cfNode" outgoingLink="//AttributeConstraintBlackPatternInvocationBuilder/calcLocalVariableName/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.0">
              <type xsi:type="ecore:EClass" href="platform:/plugin/ControlFlow/model/ControlFlow.ecore#//CFNode"/>
            </objectVariable>
            <objectVariable name="variable" bindingState="BOUND">
              <type xsi:type="ecore:EClass" href="http://gervarro.org/democles/specification.ecore#//Variable"/>
            </objectVariable>
            <objectVariable name="builder" outgoingLink="//AttributeConstraintBlackPatternInvocationBuilder/calcLocalVariableName/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.1" bindingState="BOUND">
              <type xsi:type="ecore:EClass" href="platform:/plugin/ScopeValidation/model/ScopeValidation.ecore#//PatternInvocationBuilder"/>
              <bindingExpression xsi:type="callExpressions:MethodCallExpression">
                <callee href="platform:/plugin/ScopeValidation/model/ScopeValidation.ecore#//RegularPatternInvocationBuilder/getPatternInvocationBuilder"/>
                <target xsi:type="patternExpressions:ObjectVariableExpression" object="//AttributeConstraintBlackPatternInvocationBuilder/calcLocalVariableName/@activity/@ownedActivityNode.3/@storyPattern/@objectVariable.0"/>
              </bindingExpression>
            </objectVariable>
            <linkVariable name="actions" target="//AttributeConstraintBlackPatternInvocationBuilder/calcLocalVariableName/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.0" source="//AttributeConstraintBlackPatternInvocationBuilder/calcLocalVariableName/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.1">
              <type href="platform:/plugin/ControlFlow/model/ControlFlow.ecore#//CFNode/actions"/>
            </linkVariable>
            <linkVariable name="result" target="//AttributeConstraintBlackPatternInvocationBuilder/calcLocalVariableName/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.0" source="//AttributeConstraintBlackPatternInvocationBuilder/calcLocalVariableName/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.3">
              <type href="platform:/plugin/ScopeValidation/model/ScopeValidation.ecore#//ActionBuilder/result"/>
            </linkVariable>
          </storyPattern>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StopNode" incoming="//AttributeConstraintBlackPatternInvocationBuilder/calcLocalVariableName/@activity/@ownedActivityEdge.1">
          <returnValue xsi:type="callExpressions:MethodCallExpression" callee="//AttributeConstraintBlackPatternInvocationBuilder/concat">
            <ownedParameterBindings parameter="//AttributeConstraintBlackPatternInvocationBuilder/concat/param1">
              <valueExpression xsi:type="patternExpressions:AttributeValueExpression" object="//AttributeConstraintBlackPatternInvocationBuilder/calcLocalVariableName/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.2">
                <attribute href="http://gervarro.org/democles/specification.ecore#//Variable/name"/>
              </valueExpression>
            </ownedParameterBindings>
            <ownedParameterBindings parameter="//AttributeConstraintBlackPatternInvocationBuilder/concat/param2">
              <valueExpression xsi:type="patternExpressions:AttributeValueExpression" object="//AttributeConstraintBlackPatternInvocationBuilder/calcLocalVariableName/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.1">
                <attribute href="platform:/plugin/ControlFlow/model/ControlFlow.ecore#//CFNode/id"/>
              </valueExpression>
            </ownedParameterBindings>
            <target xsi:type="patternExpressions:ObjectVariableExpression" object="//AttributeConstraintBlackPatternInvocationBuilder/calcLocalVariableName/@activity/@ownedActivityNode.3/@storyPattern/@objectVariable.0"/>
          </returnValue>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StoryNode" name="ActivityNode8" comment="ActivityNode8" outgoing="//AttributeConstraintBlackPatternInvocationBuilder/calcLocalVariableName/@activity/@ownedActivityEdge.2" incoming="//AttributeConstraintBlackPatternInvocationBuilder/calcLocalVariableName/@activity/@ownedActivityEdge.0">
          <storyPattern comment="ActivityNode8">
            <objectVariable type="//AttributeConstraintBlackPatternInvocationBuilder" name="this" bindingState="BOUND"/>
          </storyPattern>
        </ownedActivityNode>
        <ownedActivityEdge source="//AttributeConstraintBlackPatternInvocationBuilder/calcLocalVariableName/@activity/@ownedActivityNode.0" target="//AttributeConstraintBlackPatternInvocationBuilder/calcLocalVariableName/@activity/@ownedActivityNode.3"/>
        <ownedActivityEdge source="//AttributeConstraintBlackPatternInvocationBuilder/calcLocalVariableName/@activity/@ownedActivityNode.1" target="//AttributeConstraintBlackPatternInvocationBuilder/calcLocalVariableName/@activity/@ownedActivityNode.2"/>
        <ownedActivityEdge source="//AttributeConstraintBlackPatternInvocationBuilder/calcLocalVariableName/@activity/@ownedActivityNode.3" target="//AttributeConstraintBlackPatternInvocationBuilder/calcLocalVariableName/@activity/@ownedActivityNode.1"/>
      </activity>
    </eOperations>
    <eOperations xsi:type="activities:MoflonEOperation" name="handleAttrVariableReference">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/ControlFlow/model/ControlFlow.ecore#//VariableReference"/>
      <eParameters name="variable">
        <eType xsi:type="ecore:EClass" href="http://gervarro.org/democles/specification.ecore#//Variable"/>
      </eParameters>
      <eParameters name="variableType">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EClassifier"/>
      </eParameters>
      <activity owningOperation="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference">
        <ownedActivityNode xsi:type="activities:StartNode" outgoing="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityEdge.0"/>
        <ownedActivityNode xsi:type="activities:StoryNode" name="LookupPatternInvocation" comment="LookupPatternInvocation" outgoing="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityEdge.1 //AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityEdge.2" incoming="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityEdge.5">
          <storyPattern comment="LookupPatternInvocation">
            <objectVariable name="correspondingBuilder" outgoingLink="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.0" bindingState="BOUND">
              <type xsi:type="ecore:EClass" href="platform:/plugin/ScopeValidation/model/ScopeValidation.ecore#//PatternInvocationBuilder"/>
              <bindingExpression xsi:type="callExpressions:MethodCallExpression">
                <callee href="platform:/plugin/ScopeValidation/model/ScopeValidation.ecore#//RegularPatternInvocationBuilder/getPatternInvocationBuilder"/>
                <target xsi:type="patternExpressions:ObjectVariableExpression" object="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityNode.5/@storyPattern/@objectVariable.0"/>
              </bindingExpression>
            </objectVariable>
            <objectVariable name="invocation" incomingLink="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.0" outgoingLink="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.1">
              <type xsi:type="ecore:EClass" href="platform:/plugin/ControlFlow/model/ControlFlow.ecore#//PatternInvocation"/>
            </objectVariable>
            <objectVariable name="democlesPattern" incomingLink="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.1" outgoingLink="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.2">
              <type xsi:type="ecore:EClass" href="http://gervarro.org/democles/specification.ecore#//Pattern"/>
            </objectVariable>
            <objectVariable name="variable" incomingLink="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.2" bindingState="BOUND">
              <type xsi:type="ecore:EClass" href="http://gervarro.org/democles/specification.ecore#//Variable"/>
            </objectVariable>
            <linkVariable name="result" target="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.1" source="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.0">
              <type href="platform:/plugin/ScopeValidation/model/ScopeValidation.ecore#//ActionBuilder/result"/>
            </linkVariable>
            <linkVariable name="pattern" target="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.2" source="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.1">
              <type href="platform:/plugin/ControlFlow/model/ControlFlow.ecore#//PatternInvocation/pattern"/>
            </linkVariable>
            <linkVariable name="symbolicParameters" target="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.3" source="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.2">
              <type href="http://gervarro.org/democles/specification.ecore#//Pattern/symbolicParameters"/>
            </linkVariable>
          </storyPattern>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StoryNode" name="LookupOrCreateControlFlowVariable" comment="LookupOrCreateControlFlowVariable" outgoing="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityEdge.3" incoming="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityEdge.1">
          <storyPattern comment="LookupOrCreateControlFlowVariable">
            <objectVariable name="cfVariable" bindingState="BOUND">
              <type xsi:type="ecore:EClass" href="platform:/plugin/ControlFlow/model/ControlFlow.ecore#//CFVariable"/>
              <bindingExpression xsi:type="callExpressions:MethodCallExpression">
                <ownedParameterBindings>
                  <valueExpression xsi:type="patternExpressions:ObjectVariableExpression" object="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.1"/>
                  <parameter href="platform:/plugin/ScopeValidation/model/ScopeValidation.ecore#//ActionBuilder/lookupControlFlowVariable/action"/>
                </ownedParameterBindings>
                <ownedParameterBindings>
                  <valueExpression xsi:type="callExpressions:MethodCallExpression" callee="//AttributeConstraintBlackPatternInvocationBuilder/calcLocalVariableName">
                    <ownedParameterBindings parameter="//AttributeConstraintBlackPatternInvocationBuilder/calcLocalVariableName/variable">
                      <valueExpression xsi:type="patternExpressions:ObjectVariableExpression" object="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityNode.3/@storyPattern/@objectVariable.0"/>
                    </ownedParameterBindings>
                    <target xsi:type="patternExpressions:ObjectVariableExpression" object="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityNode.5/@storyPattern/@objectVariable.0"/>
                  </valueExpression>
                  <parameter href="platform:/plugin/ScopeValidation/model/ScopeValidation.ecore#//ActionBuilder/lookupControlFlowVariable/variableName"/>
                </ownedParameterBindings>
                <ownedParameterBindings>
                  <valueExpression xsi:type="callExpressions:ParameterExpression" parameter="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/variableType"/>
                  <parameter href="platform:/plugin/ScopeValidation/model/ScopeValidation.ecore#//ActionBuilder/lookupControlFlowVariable/variableType"/>
                </ownedParameterBindings>
                <callee href="platform:/plugin/ScopeValidation/model/ScopeValidation.ecore#//ActionBuilder/lookupControlFlowVariable"/>
                <target xsi:type="patternExpressions:ObjectVariableExpression" object="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityNode.5/@storyPattern/@objectVariable.0"/>
              </bindingExpression>
            </objectVariable>
          </storyPattern>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StoryNode" name="CreateVariableReference" comment="CreateVariableReference" outgoing="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityEdge.4" incoming="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityEdge.3">
          <storyPattern comment="CreateVariableReference">
            <objectVariable name="variable" incomingLink="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityNode.3/@storyPattern/@linkVariable.2" bindingState="BOUND">
              <type xsi:type="ecore:EClass" href="http://gervarro.org/democles/specification.ecore#//Variable"/>
            </objectVariable>
            <objectVariable name="invocation" incomingLink="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityNode.3/@storyPattern/@linkVariable.0" bindingState="BOUND">
              <type xsi:type="ecore:EClass" href="platform:/plugin/ControlFlow/model/ControlFlow.ecore#//PatternInvocation"/>
            </objectVariable>
            <objectVariable name="cfVariable" incomingLink="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityNode.3/@storyPattern/@linkVariable.1" bindingState="BOUND">
              <type xsi:type="ecore:EClass" href="platform:/plugin/ControlFlow/model/ControlFlow.ecore#//CFVariable"/>
              <attributeAssignment>
                <attribute href="platform:/plugin/ControlFlow/model/ControlFlow.ecore#//CFVariable/local"/>
                <valueExpression xsi:type="expressions:LiteralExpression" value="true"/>
              </attributeAssignment>
            </objectVariable>
            <objectVariable name="newReference" outgoingLink="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityNode.3/@storyPattern/@linkVariable.1 //AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityNode.3/@storyPattern/@linkVariable.2 //AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityNode.3/@storyPattern/@linkVariable.0" bindingOperator="CREATE">
              <type xsi:type="ecore:EClass" href="platform:/plugin/ControlFlow/model/ControlFlow.ecore#//VariableReference"/>
            </objectVariable>
            <linkVariable name="invocation" target="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityNode.3/@storyPattern/@objectVariable.1" source="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityNode.3/@storyPattern/@objectVariable.3" bindingOperator="CREATE">
              <type href="platform:/plugin/ControlFlow/model/ControlFlow.ecore#//VariableReference/invocation"/>
            </linkVariable>
            <linkVariable name="from" target="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityNode.3/@storyPattern/@objectVariable.2" source="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityNode.3/@storyPattern/@objectVariable.3" bindingOperator="CREATE">
              <type href="platform:/plugin/ControlFlow/model/ControlFlow.ecore#//VariableReference/from"/>
            </linkVariable>
            <linkVariable name="to" target="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityNode.3/@storyPattern/@objectVariable.0" source="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityNode.3/@storyPattern/@objectVariable.3" bindingOperator="CREATE">
              <type href="platform:/plugin/ControlFlow/model/ControlFlow.ecore#//VariableReference/to"/>
            </linkVariable>
          </storyPattern>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StopNode" incoming="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityEdge.4">
          <returnValue xsi:type="patternExpressions:ObjectVariableExpression" object="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityNode.3/@storyPattern/@objectVariable.3"/>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StoryNode" name="ActivityNode7" comment="ActivityNode7" outgoing="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityEdge.5" incoming="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityEdge.0">
          <storyPattern comment="ActivityNode7">
            <objectVariable type="//AttributeConstraintBlackPatternInvocationBuilder" name="this" bindingState="BOUND"/>
          </storyPattern>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StopNode" incoming="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityEdge.2">
          <returnValue xsi:type="expressions:LiteralExpression" value="null"/>
        </ownedActivityNode>
        <ownedActivityEdge source="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityNode.0" target="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityNode.5"/>
        <ownedActivityEdge source="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityNode.1" target="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityNode.2" guard="SUCCESS"/>
        <ownedActivityEdge source="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityNode.1" target="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityNode.6" guard="FAILURE"/>
        <ownedActivityEdge source="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityNode.2" target="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityNode.3"/>
        <ownedActivityEdge source="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityNode.3" target="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityNode.4"/>
        <ownedActivityEdge source="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityNode.5" target="//AttributeConstraintBlackPatternInvocationBuilder/handleAttrVariableReference/@activity/@ownedActivityNode.1"/>
      </activity>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeConstraintGreenPatternInvocationBuilder" eSuperTypes="//AttributeConstraintBlackPatternInvocationBuilder">
    <eOperations xsi:type="activities:MoflonEOperation" name="validateVariable">
      <eParameters name="action">
        <eType xsi:type="ecore:EClass" href="platform:/plugin/ControlFlow/model/ControlFlow.ecore#//Action"/>
      </eParameters>
      <eParameters name="variable">
        <eType xsi:type="ecore:EClass" href="platform:/plugin/ControlFlow/model/ControlFlow.ecore#//CFVariable"/>
      </eParameters>
      <eParameters name="objectVariable">
        <eType xsi:type="ecore:EClass" href="platform:/plugin/SDMLanguage/model/SDMLanguage.ecore#//patterns/ObjectVariable"/>
      </eParameters>
      <activity owningOperation="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable">
        <ownedActivityNode xsi:type="activities:StartNode" outgoing="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityEdge.0"/>
        <ownedActivityNode xsi:type="activities:StoryNode" name="ReportErrorByNonGreenFreeVariables" comment="ReportErrorByNonGreenFreeVariables" outgoing="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityEdge.1" incoming="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityEdge.5">
          <storyPattern comment="ReportErrorByNonGreenFreeVariables">
            <objectVariable type="//AttributeConstraintGreenPatternInvocationBuilder" name="this" bindingState="BOUND"/>
            <objectVariable name="scopeValidator" outgoingLink="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.0" bindingState="BOUND">
              <type xsi:type="ecore:EClass" href="platform:/plugin/ScopeValidation/model/ScopeValidation.ecore#//ScopeValidator"/>
              <bindingExpression xsi:type="callExpressions:MethodCallExpression">
                <callee href="platform:/plugin/ScopeValidation/model/ScopeValidation.ecore#//RegularPatternInvocationBuilder/lookupScopeValidator"/>
                <target xsi:type="patternExpressions:ObjectVariableExpression" object="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.0"/>
              </bindingExpression>
            </objectVariable>
            <objectVariable name="report" incomingLink="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.0" outgoingLink="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.2">
              <type xsi:type="ecore:EClass" href="platform:/plugin/org.moflon.sdm.compiler.democles.validation.result/model/Result.ecore#//ValidationReport"/>
            </objectVariable>
            <objectVariable name="objectVariable" incomingLink="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.1" bindingState="BOUND">
              <type xsi:type="ecore:EClass" href="platform:/plugin/SDMLanguage/model/SDMLanguage.ecore#//patterns/ObjectVariable"/>
            </objectVariable>
            <objectVariable name="errorGreenNotFree" incomingLink="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.2" outgoingLink="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.1" bindingOperator="CREATE">
              <type xsi:type="ecore:EClass" href="platform:/plugin/org.moflon.sdm.compiler.democles.validation.result/model/Result.ecore#//ErrorMessage"/>
              <attributeAssignment>
                <attribute href="platform:/plugin/org.moflon.sdm.compiler.democles.validation.result/model/Result.ecore#//ErrorMessage/severity"/>
                <valueExpression xsi:type="expressions:LiteralExpression" value="ValidationResult.Severity.ERROR"/>
              </attributeAssignment>
              <attributeAssignment>
                <attribute href="platform:/plugin/org.moflon.sdm.compiler.democles.validation.result/model/Result.ecore#//ErrorMessage/id"/>
                <valueExpression xsi:type="callExpressions:MethodCallExpression">
                  <ownedParameterBindings>
                    <valueExpression xsi:type="expressions:LiteralExpression" value="ScopeValidation.Errors.GREEN_VAR_IS_NOT_NEW"/>
                    <parameter href="platform:/plugin/ScopeValidation/model/ScopeValidation.ecore#//ScopeValidator/lookupErrorMessage/errorID"/>
                  </ownedParameterBindings>
                  <callee href="platform:/plugin/ScopeValidation/model/ScopeValidation.ecore#//ScopeValidator/lookupErrorMessage"/>
                  <target xsi:type="patternExpressions:ObjectVariableExpression" object="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.1"/>
                </valueExpression>
              </attributeAssignment>
            </objectVariable>
            <linkVariable name="validationReport" target="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.2" source="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.1">
              <type href="platform:/plugin/ScopeValidation/model/ScopeValidation.ecore#//ScopeValidator/validationReport"/>
            </linkVariable>
            <linkVariable name="location" target="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.3" source="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.4" bindingOperator="CREATE">
              <type href="platform:/plugin/org.moflon.sdm.compiler.democles.validation.result/model/Result.ecore#//ErrorMessage/location"/>
            </linkVariable>
            <linkVariable name="errorMessages" target="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.4" source="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.2" bindingOperator="CREATE">
              <type href="platform:/plugin/org.moflon.sdm.compiler.democles.validation.result/model/Result.ecore#//ValidationReport/errorMessages"/>
            </linkVariable>
          </storyPattern>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StoryNode" name="IsVariableFree" comment="IsVariableFree" outgoing="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityEdge.2 //AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityEdge.3" incoming="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityEdge.0">
          <storyPattern comment="IsVariableFree">
            <objectVariable name="action" incomingLink="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityNode.2/@storyPattern/@linkVariable.0" bindingState="BOUND">
              <type xsi:type="ecore:EClass" href="platform:/plugin/ControlFlow/model/ControlFlow.ecore#//Action"/>
            </objectVariable>
            <objectVariable name="variable" outgoingLink="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityNode.2/@storyPattern/@linkVariable.0" bindingState="BOUND">
              <type xsi:type="ecore:EClass" href="platform:/plugin/ControlFlow/model/ControlFlow.ecore#//CFVariable"/>
            </objectVariable>
            <linkVariable name="constructor" target="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityNode.2/@storyPattern/@objectVariable.0" source="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityNode.2/@storyPattern/@objectVariable.1">
              <type href="platform:/plugin/ControlFlow/model/ControlFlow.ecore#//CFVariable/constructor"/>
            </linkVariable>
          </storyPattern>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StoryNode" name="IsGreenVariable" comment="IsGreenVariable" outgoing="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityEdge.4 //AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityEdge.5" incoming="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityEdge.3">
          <storyPattern comment="IsGreenVariable">
            <objectVariable name="objectVariable" bindingState="BOUND">
              <type xsi:type="ecore:EClass" href="platform:/plugin/SDMLanguage/model/SDMLanguage.ecore#//patterns/ObjectVariable"/>
              <constraint>
                <constraintExpression xsi:type="expressions:ComparisonExpression" operator="EQUAL">
                  <rightExpression xsi:type="expressions:LiteralExpression" value="SDMLanguage.patterns.BindingOperator.CREATE"/>
                  <leftExpression xsi:type="patternExpressions:AttributeValueExpression" object="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityNode.3/@storyPattern/@objectVariable.0">
                    <attribute href="platform:/plugin/SDMLanguage/model/SDMLanguage.ecore#//patterns/ObjectVariable/bindingOperator"/>
                  </leftExpression>
                </constraintExpression>
              </constraint>
            </objectVariable>
          </storyPattern>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StopNode" incoming="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityEdge.4"/>
        <ownedActivityNode xsi:type="activities:StopNode" incoming="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityEdge.1"/>
        <ownedActivityNode xsi:type="activities:StoryNode" name="IsBlackVariable" comment="IsBlackVariable" outgoing="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityEdge.6 //AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityEdge.7" incoming="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityEdge.2">
          <storyPattern comment="IsBlackVariable">
            <objectVariable name="objectVariable" bindingState="BOUND">
              <type xsi:type="ecore:EClass" href="platform:/plugin/SDMLanguage/model/SDMLanguage.ecore#//patterns/ObjectVariable"/>
              <constraint>
                <constraintExpression xsi:type="expressions:ComparisonExpression" operator="EQUAL">
                  <rightExpression xsi:type="expressions:LiteralExpression" value="SDMLanguage.patterns.BindingOperator.CHECK_ONLY"/>
                  <leftExpression xsi:type="patternExpressions:AttributeValueExpression" object="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityNode.6/@storyPattern/@objectVariable.0">
                    <attribute href="platform:/plugin/SDMLanguage/model/SDMLanguage.ecore#//patterns/ObjectVariable/bindingOperator"/>
                  </leftExpression>
                </constraintExpression>
              </constraint>
            </objectVariable>
          </storyPattern>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StopNode" incoming="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityEdge.7"/>
        <ownedActivityNode xsi:type="activities:StoryNode" name="ReportErrorByNonBlackBoundVariables" comment="ReportErrorByNonBlackBoundVariables" outgoing="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityEdge.8" incoming="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityEdge.6">
          <storyPattern comment="ReportErrorByNonBlackBoundVariables"/>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StopNode" incoming="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityEdge.8"/>
        <ownedActivityEdge source="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityNode.0" target="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityNode.2"/>
        <ownedActivityEdge source="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityNode.1" target="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityNode.5"/>
        <ownedActivityEdge source="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityNode.2" target="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityNode.6" guard="FAILURE"/>
        <ownedActivityEdge source="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityNode.2" target="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityNode.3" guard="SUCCESS"/>
        <ownedActivityEdge source="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityNode.3" target="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityNode.4" guard="SUCCESS"/>
        <ownedActivityEdge source="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityNode.3" target="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityNode.1" guard="FAILURE"/>
        <ownedActivityEdge source="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityNode.6" target="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityNode.8" guard="FAILURE"/>
        <ownedActivityEdge source="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityNode.6" target="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityNode.7" guard="SUCCESS"/>
        <ownedActivityEdge source="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityNode.8" target="//AttributeConstraintGreenPatternInvocationBuilder/validateVariable/@activity/@ownedActivityNode.9"/>
      </activity>
    </eOperations>
  </eClassifiers>
</ecore:EPackage>
