<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tggcpa" nsURI="platform:/plugin/org.moflon.maave.tests.lang.tggcpa/model/Tggcpa.ecore" nsPrefix="org.moflon.maave.tests.lang.tggcpa">
  <eClassifiers xsi:type="ecore:EClass" name="Obj"/>
  <eClassifiers xsi:type="ecore:EClass" name="Transl"/>
  <eClassifiers xsi:type="ecore:EClass" name="TypeA">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1" eType="//TypeB"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transl" eType="//Transl"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeB">
    <eStructuralFeatures xsi:type="ecore:EReference" name="transl" eType="//Transl"/>
  </eClassifiers>
</ecore:EPackage>
