<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:AttributeConstraints="platform:/plugin/SDMLanguage/model/SDMLanguage.ecore#//patterns/AttributeConstraints" xmlns:activities="platform:/plugin/SDMLanguage/model/SDMLanguage.ecore#//activities" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="genfeaturemodel" nsURI="platform:/plugin/org.moflon.maave.tests.testgen.genfeaturemodel/model/Genfeaturemodel.ecore" nsPrefix="org.moflon.maave.tests.testgen.genfeaturemodel">
  <eClassifiers xsi:type="ecore:EClass" name="Rules">
    <eOperations xsi:type="activities:MoflonEOperation" name="ruleA">
      <eParameters name="f1">
        <eType xsi:type="ecore:EClass" href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//Feature"/>
      </eParameters>
      <activity owningOperation="//Rules/ruleA">
        <ownedActivityNode xsi:type="activities:StartNode" outgoing="//Rules/ruleA/@activity/@ownedActivityEdge.0"/>
        <ownedActivityNode xsi:type="activities:StoryNode" name="ActivityNode1" comment="ActivityNode1" outgoing="//Rules/ruleA/@activity/@ownedActivityEdge.1" incoming="//Rules/ruleA/@activity/@ownedActivityEdge.0">
          <storyPattern comment="ActivityNode1">
            <objectVariable name="f1" outgoingLink="//Rules/ruleA/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.0 //Rules/ruleA/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.1" bindingState="BOUND">
              <type xsi:type="ecore:EClass" href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//Feature"/>
            </objectVariable>
            <objectVariable name="man" incomingLink="//Rules/ruleA/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.0" outgoingLink="//Rules/ruleA/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.2" bindingOperator="DESTROY">
              <type xsi:type="ecore:EClass" href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//Group"/>
            </objectVariable>
            <objectVariable name="f2" incomingLink="//Rules/ruleA/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.2" outgoingLink="//Rules/ruleA/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.3" bindingOperator="DESTROY">
              <type xsi:type="ecore:EClass" href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//Feature"/>
            </objectVariable>
            <objectVariable name="a2" incomingLink="//Rules/ruleA/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.3" bindingOperator="DESTROY">
              <type xsi:type="ecore:EClass" href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//NatFeatureAttribute"/>
            </objectVariable>
            <objectVariable name="a1" incomingLink="//Rules/ruleA/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.1" bindingOperator="CREATE">
              <type xsi:type="ecore:EClass" href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//NatFeatureAttribute"/>
            </objectVariable>
            <linkVariable name="groups" target="//Rules/ruleA/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.1" source="//Rules/ruleA/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.0" bindingOperator="DESTROY">
              <type href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//Feature/groups"/>
            </linkVariable>
            <linkVariable name="nat" target="//Rules/ruleA/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.4" source="//Rules/ruleA/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.0" bindingOperator="CREATE">
              <type href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//Feature/nat"/>
            </linkVariable>
            <linkVariable name="features" target="//Rules/ruleA/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.2" source="//Rules/ruleA/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.1" bindingOperator="DESTROY">
              <type href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//Group/features"/>
            </linkVariable>
            <linkVariable name="nat" target="//Rules/ruleA/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.3" source="//Rules/ruleA/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.2" bindingOperator="DESTROY">
              <type href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//Feature/nat"/>
            </linkVariable>
            <constraints xsi:type="AttributeConstraints:CspConstraint" parameters="//Rules/ruleA/@activity/@ownedActivityNode.1/@storyPattern/@variables.0 //Rules/ruleA/@activity/@ownedActivityNode.1/@storyPattern/@variables.1" name="="/>
            <constraints xsi:type="AttributeConstraints:AttributeLookupConstraint" parameter="//Rules/ruleA/@activity/@ownedActivityNode.1/@storyPattern/@variables.0" objectVariable="//Rules/ruleA/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.1">
              <type href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//Group/type"/>
            </constraints>
            <constraints xsi:type="AttributeConstraints:CspConstraint" parameters="//Rules/ruleA/@activity/@ownedActivityNode.1/@storyPattern/@variables.2 //Rules/ruleA/@activity/@ownedActivityNode.1/@storyPattern/@variables.3 //Rules/ruleA/@activity/@ownedActivityNode.1/@storyPattern/@variables.4" name="IMPL?"/>
            <constraints xsi:type="AttributeConstraints:AttributeLookupConstraint" parameter="//Rules/ruleA/@activity/@ownedActivityNode.1/@storyPattern/@variables.2" objectVariable="//Rules/ruleA/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.0">
              <type href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//Feature/sel"/>
            </constraints>
            <constraints xsi:type="AttributeConstraints:CspConstraint" parameters="//Rules/ruleA/@activity/@ownedActivityNode.1/@storyPattern/@variables.5 //Rules/ruleA/@activity/@ownedActivityNode.1/@storyPattern/@variables.6 //Rules/ruleA/@activity/@ownedActivityNode.1/@storyPattern/@variables.3" name="=?"/>
            <constraints xsi:type="AttributeConstraints:AssignmentConstraint" parameter="//Rules/ruleA/@activity/@ownedActivityNode.1/@storyPattern/@variables.5" objectVariable="//Rules/ruleA/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.4">
              <type href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//NatFeatureAttribute/val"/>
            </constraints>
            <constraints xsi:type="AttributeConstraints:AttributeLookupConstraint" parameter="//Rules/ruleA/@activity/@ownedActivityNode.1/@storyPattern/@variables.6" objectVariable="//Rules/ruleA/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.3">
              <type href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//NatFeatureAttribute/val"/>
            </constraints>
            <variables xsi:type="AttributeConstraints:PrimitiveVariable" cspConstraints="//Rules/ruleA/@activity/@ownedActivityNode.1/@storyPattern/@constraints.0" attributeValueConstraints="//Rules/ruleA/@activity/@ownedActivityNode.1/@storyPattern/@constraints.1" name="man_type">
              <type href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
            </variables>
            <variables xsi:type="AttributeConstraints:LiteralVariable" cspConstraints="//Rules/ruleA/@activity/@ownedActivityNode.1/@storyPattern/@constraints.0" name="3">
              <type href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
            </variables>
            <variables xsi:type="AttributeConstraints:PrimitiveVariable" cspConstraints="//Rules/ruleA/@activity/@ownedActivityNode.1/@storyPattern/@constraints.2" attributeValueConstraints="//Rules/ruleA/@activity/@ownedActivityNode.1/@storyPattern/@constraints.3" name="f1_sel">
              <type href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
            </variables>
            <variables xsi:type="AttributeConstraints:PrimitiveVariable" cspConstraints="//Rules/ruleA/@activity/@ownedActivityNode.1/@storyPattern/@constraints.2 //Rules/ruleA/@activity/@ownedActivityNode.1/@storyPattern/@constraints.4" name="v1EQv2">
              <type href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
            </variables>
            <variables xsi:type="AttributeConstraints:LiteralVariable" cspConstraints="//Rules/ruleA/@activity/@ownedActivityNode.1/@storyPattern/@constraints.2" name="true">
              <type href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
            </variables>
            <variables xsi:type="AttributeConstraints:PrimitiveVariable" cspConstraints="//Rules/ruleA/@activity/@ownedActivityNode.1/@storyPattern/@constraints.4" attributeValueConstraints="//Rules/ruleA/@activity/@ownedActivityNode.1/@storyPattern/@constraints.5" name="a1_val_prime">
              <type href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
            </variables>
            <variables xsi:type="AttributeConstraints:PrimitiveVariable" cspConstraints="//Rules/ruleA/@activity/@ownedActivityNode.1/@storyPattern/@constraints.4" attributeValueConstraints="//Rules/ruleA/@activity/@ownedActivityNode.1/@storyPattern/@constraints.6" name="a2_val">
              <type href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
            </variables>
          </storyPattern>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StopNode" incoming="//Rules/ruleA/@activity/@ownedActivityEdge.1"/>
        <ownedActivityEdge source="//Rules/ruleA/@activity/@ownedActivityNode.0" target="//Rules/ruleA/@activity/@ownedActivityNode.1"/>
        <ownedActivityEdge source="//Rules/ruleA/@activity/@ownedActivityNode.1" target="//Rules/ruleA/@activity/@ownedActivityNode.2"/>
      </activity>
    </eOperations>
    <eOperations xsi:type="activities:MoflonEOperation" name="ruleB">
      <eParameters name="fx">
        <eType xsi:type="ecore:EClass" href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//Feature"/>
      </eParameters>
      <activity owningOperation="//Rules/ruleB">
        <ownedActivityNode xsi:type="activities:StartNode" outgoing="//Rules/ruleB/@activity/@ownedActivityEdge.0"/>
        <ownedActivityNode xsi:type="activities:StoryNode" name="ActivityNode2" comment="ActivityNode2" outgoing="//Rules/ruleB/@activity/@ownedActivityEdge.1" incoming="//Rules/ruleB/@activity/@ownedActivityEdge.0">
          <storyPattern comment="ActivityNode2">
            <objectVariable name="fx" outgoingLink="//Rules/ruleB/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.0" bindingState="BOUND">
              <type xsi:type="ecore:EClass" href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//Feature"/>
            </objectVariable>
            <objectVariable name="ax" incomingLink="//Rules/ruleB/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.0">
              <type xsi:type="ecore:EClass" href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//NatFeatureAttribute"/>
            </objectVariable>
            <linkVariable name="nat" target="//Rules/ruleB/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.1" source="//Rules/ruleB/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.0">
              <type href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//Feature/nat"/>
            </linkVariable>
            <constraints xsi:type="AttributeConstraints:CspConstraint" parameters="//Rules/ruleB/@activity/@ownedActivityNode.1/@storyPattern/@variables.0 //Rules/ruleB/@activity/@ownedActivityNode.1/@storyPattern/@variables.1 //Rules/ruleB/@activity/@ownedActivityNode.1/@storyPattern/@variables.2" name="+"/>
            <constraints xsi:type="AttributeConstraints:AssignmentConstraint" parameter="//Rules/ruleB/@activity/@ownedActivityNode.1/@storyPattern/@variables.0" objectVariable="//Rules/ruleB/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.1">
              <type href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//NatFeatureAttribute/val"/>
            </constraints>
            <constraints xsi:type="AttributeConstraints:AttributeLookupConstraint" parameter="//Rules/ruleB/@activity/@ownedActivityNode.1/@storyPattern/@variables.1" objectVariable="//Rules/ruleB/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.1">
              <type href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//NatFeatureAttribute/val"/>
            </constraints>
            <constraints xsi:type="AttributeConstraints:CspConstraint" parameters="//Rules/ruleB/@activity/@ownedActivityNode.1/@storyPattern/@variables.2 //Rules/ruleB/@activity/@ownedActivityNode.1/@storyPattern/@variables.1" name="="/>
            <variables xsi:type="AttributeConstraints:PrimitiveVariable" cspConstraints="//Rules/ruleB/@activity/@ownedActivityNode.1/@storyPattern/@constraints.0" attributeValueConstraints="//Rules/ruleB/@activity/@ownedActivityNode.1/@storyPattern/@constraints.1" name="ax_val_prime">
              <type href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
            </variables>
            <variables xsi:type="AttributeConstraints:PrimitiveVariable" cspConstraints="//Rules/ruleB/@activity/@ownedActivityNode.1/@storyPattern/@constraints.0 //Rules/ruleB/@activity/@ownedActivityNode.1/@storyPattern/@constraints.3" attributeValueConstraints="//Rules/ruleB/@activity/@ownedActivityNode.1/@storyPattern/@constraints.2" name="ax_val">
              <type href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
            </variables>
            <variables xsi:type="AttributeConstraints:PrimitiveVariable" cspConstraints="//Rules/ruleB/@activity/@ownedActivityNode.1/@storyPattern/@constraints.0 //Rules/ruleB/@activity/@ownedActivityNode.1/@storyPattern/@constraints.3" name="temp">
              <type href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
            </variables>
          </storyPattern>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StopNode" incoming="//Rules/ruleB/@activity/@ownedActivityEdge.1"/>
        <ownedActivityEdge source="//Rules/ruleB/@activity/@ownedActivityNode.0" target="//Rules/ruleB/@activity/@ownedActivityNode.1"/>
        <ownedActivityEdge source="//Rules/ruleB/@activity/@ownedActivityNode.1" target="//Rules/ruleB/@activity/@ownedActivityNode.2"/>
      </activity>
    </eOperations>
    <eOperations xsi:type="activities:MoflonEOperation" name="ruleC">
      <eParameters name="fy">
        <eType xsi:type="ecore:EClass" href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//Feature"/>
      </eParameters>
      <activity owningOperation="//Rules/ruleC">
        <ownedActivityNode xsi:type="activities:StartNode" outgoing="//Rules/ruleC/@activity/@ownedActivityEdge.0"/>
        <ownedActivityNode xsi:type="activities:StoryNode" name="ActivityNode3" comment="ActivityNode3" outgoing="//Rules/ruleC/@activity/@ownedActivityEdge.1" incoming="//Rules/ruleC/@activity/@ownedActivityEdge.0">
          <storyPattern comment="ActivityNode3">
            <objectVariable name="fy" outgoingLink="//Rules/ruleC/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.0" bindingState="BOUND">
              <type xsi:type="ecore:EClass" href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//Feature"/>
            </objectVariable>
            <objectVariable name="ay" incomingLink="//Rules/ruleC/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.0">
              <type xsi:type="ecore:EClass" href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//NatFeatureAttribute"/>
            </objectVariable>
            <linkVariable name="nat" target="//Rules/ruleC/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.1" source="//Rules/ruleC/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.0">
              <type href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//Feature/nat"/>
            </linkVariable>
            <constraints xsi:type="AttributeConstraints:CspConstraint" parameters="//Rules/ruleC/@activity/@ownedActivityNode.1/@storyPattern/@variables.0 //Rules/ruleC/@activity/@ownedActivityNode.1/@storyPattern/@variables.1 //Rules/ruleC/@activity/@ownedActivityNode.1/@storyPattern/@variables.2" name="+"/>
            <constraints xsi:type="AttributeConstraints:AttributeLookupConstraint" parameter="//Rules/ruleC/@activity/@ownedActivityNode.1/@storyPattern/@variables.0" objectVariable="//Rules/ruleC/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.1">
              <type href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//NatFeatureAttribute/val"/>
            </constraints>
            <constraints xsi:type="AttributeConstraints:AssignmentConstraint" parameter="//Rules/ruleC/@activity/@ownedActivityNode.1/@storyPattern/@variables.1" objectVariable="//Rules/ruleC/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.1">
              <type href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//NatFeatureAttribute/val"/>
            </constraints>
            <variables xsi:type="AttributeConstraints:PrimitiveVariable" cspConstraints="//Rules/ruleC/@activity/@ownedActivityNode.1/@storyPattern/@constraints.0" attributeValueConstraints="//Rules/ruleC/@activity/@ownedActivityNode.1/@storyPattern/@constraints.1" name="ay_val">
              <type href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
            </variables>
            <variables xsi:type="AttributeConstraints:PrimitiveVariable" cspConstraints="//Rules/ruleC/@activity/@ownedActivityNode.1/@storyPattern/@constraints.0" attributeValueConstraints="//Rules/ruleC/@activity/@ownedActivityNode.1/@storyPattern/@constraints.2" name="ay_val_prime">
              <type href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
            </variables>
            <variables xsi:type="AttributeConstraints:LiteralVariable" cspConstraints="//Rules/ruleC/@activity/@ownedActivityNode.1/@storyPattern/@constraints.0" name="10">
              <type href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
            </variables>
          </storyPattern>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StopNode" incoming="//Rules/ruleC/@activity/@ownedActivityEdge.1"/>
        <ownedActivityEdge source="//Rules/ruleC/@activity/@ownedActivityNode.0" target="//Rules/ruleC/@activity/@ownedActivityNode.1"/>
        <ownedActivityEdge source="//Rules/ruleC/@activity/@ownedActivityNode.1" target="//Rules/ruleC/@activity/@ownedActivityNode.2"/>
      </activity>
    </eOperations>
    <eOperations xsi:type="activities:MoflonEOperation" name="ruleA2">
      <eParameters name="f1">
        <eType xsi:type="ecore:EClass" href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//Feature"/>
      </eParameters>
      <activity owningOperation="//Rules/ruleA2">
        <ownedActivityNode xsi:type="activities:StartNode" outgoing="//Rules/ruleA2/@activity/@ownedActivityEdge.0"/>
        <ownedActivityNode xsi:type="activities:StoryNode" name="ActivityNode1" comment="ActivityNode1" outgoing="//Rules/ruleA2/@activity/@ownedActivityEdge.1" incoming="//Rules/ruleA2/@activity/@ownedActivityEdge.0">
          <storyPattern comment="ActivityNode1">
            <objectVariable name="f1" outgoingLink="//Rules/ruleA2/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.0 //Rules/ruleA2/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.1" bindingState="BOUND">
              <type xsi:type="ecore:EClass" href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//Feature"/>
            </objectVariable>
            <objectVariable name="man" incomingLink="//Rules/ruleA2/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.0" outgoingLink="//Rules/ruleA2/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.2" bindingOperator="DESTROY">
              <type xsi:type="ecore:EClass" href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//Group"/>
            </objectVariable>
            <objectVariable name="f2" incomingLink="//Rules/ruleA2/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.2" outgoingLink="//Rules/ruleA2/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.3" bindingOperator="DESTROY">
              <type xsi:type="ecore:EClass" href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//Feature"/>
            </objectVariable>
            <objectVariable name="a2" incomingLink="//Rules/ruleA2/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.3" bindingOperator="DESTROY">
              <type xsi:type="ecore:EClass" href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//RealFeatureAttribute"/>
            </objectVariable>
            <objectVariable name="a1" incomingLink="//Rules/ruleA2/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.1" bindingOperator="CREATE">
              <type xsi:type="ecore:EClass" href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//RealFeatureAttribute"/>
            </objectVariable>
            <linkVariable name="groups" target="//Rules/ruleA2/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.1" source="//Rules/ruleA2/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.0" bindingOperator="DESTROY">
              <type href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//Feature/groups"/>
            </linkVariable>
            <linkVariable name="real" target="//Rules/ruleA2/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.4" source="//Rules/ruleA2/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.0" bindingOperator="CREATE">
              <type href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//Feature/real"/>
            </linkVariable>
            <linkVariable name="features" target="//Rules/ruleA2/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.2" source="//Rules/ruleA2/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.1" bindingOperator="DESTROY">
              <type href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//Group/features"/>
            </linkVariable>
            <linkVariable name="real" target="//Rules/ruleA2/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.3" source="//Rules/ruleA2/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.2" bindingOperator="DESTROY">
              <type href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//Feature/real"/>
            </linkVariable>
            <constraints xsi:type="AttributeConstraints:CspConstraint" parameters="//Rules/ruleA2/@activity/@ownedActivityNode.1/@storyPattern/@variables.0 //Rules/ruleA2/@activity/@ownedActivityNode.1/@storyPattern/@variables.1" name="="/>
            <constraints xsi:type="AttributeConstraints:AttributeLookupConstraint" parameter="//Rules/ruleA2/@activity/@ownedActivityNode.1/@storyPattern/@variables.0" objectVariable="//Rules/ruleA2/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.1">
              <type href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//Group/type"/>
            </constraints>
            <constraints xsi:type="AttributeConstraints:CspConstraint" parameters="//Rules/ruleA2/@activity/@ownedActivityNode.1/@storyPattern/@variables.2 //Rules/ruleA2/@activity/@ownedActivityNode.1/@storyPattern/@variables.3 //Rules/ruleA2/@activity/@ownedActivityNode.1/@storyPattern/@variables.4" name="IMPL?"/>
            <constraints xsi:type="AttributeConstraints:AttributeLookupConstraint" parameter="//Rules/ruleA2/@activity/@ownedActivityNode.1/@storyPattern/@variables.2" objectVariable="//Rules/ruleA2/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.0">
              <type href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//Feature/sel"/>
            </constraints>
            <constraints xsi:type="AttributeConstraints:CspConstraint" parameters="//Rules/ruleA2/@activity/@ownedActivityNode.1/@storyPattern/@variables.5 //Rules/ruleA2/@activity/@ownedActivityNode.1/@storyPattern/@variables.6 //Rules/ruleA2/@activity/@ownedActivityNode.1/@storyPattern/@variables.3" name="=?"/>
            <constraints xsi:type="AttributeConstraints:AssignmentConstraint" parameter="//Rules/ruleA2/@activity/@ownedActivityNode.1/@storyPattern/@variables.5" objectVariable="//Rules/ruleA2/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.4">
              <type href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//RealFeatureAttribute/val"/>
            </constraints>
            <constraints xsi:type="AttributeConstraints:AttributeLookupConstraint" parameter="//Rules/ruleA2/@activity/@ownedActivityNode.1/@storyPattern/@variables.6" objectVariable="//Rules/ruleA2/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.3">
              <type href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//RealFeatureAttribute/val"/>
            </constraints>
            <variables xsi:type="AttributeConstraints:PrimitiveVariable" cspConstraints="//Rules/ruleA2/@activity/@ownedActivityNode.1/@storyPattern/@constraints.0" attributeValueConstraints="//Rules/ruleA2/@activity/@ownedActivityNode.1/@storyPattern/@constraints.1" name="man_type">
              <type href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
            </variables>
            <variables xsi:type="AttributeConstraints:LiteralVariable" cspConstraints="//Rules/ruleA2/@activity/@ownedActivityNode.1/@storyPattern/@constraints.0" name="3">
              <type href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
            </variables>
            <variables xsi:type="AttributeConstraints:PrimitiveVariable" cspConstraints="//Rules/ruleA2/@activity/@ownedActivityNode.1/@storyPattern/@constraints.2" attributeValueConstraints="//Rules/ruleA2/@activity/@ownedActivityNode.1/@storyPattern/@constraints.3" name="f1_sel">
              <type href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
            </variables>
            <variables xsi:type="AttributeConstraints:PrimitiveVariable" cspConstraints="//Rules/ruleA2/@activity/@ownedActivityNode.1/@storyPattern/@constraints.2 //Rules/ruleA2/@activity/@ownedActivityNode.1/@storyPattern/@constraints.4" name="v1EQv2">
              <type href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
            </variables>
            <variables xsi:type="AttributeConstraints:LiteralVariable" cspConstraints="//Rules/ruleA2/@activity/@ownedActivityNode.1/@storyPattern/@constraints.2" name="true">
              <type href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
            </variables>
            <variables xsi:type="AttributeConstraints:PrimitiveVariable" cspConstraints="//Rules/ruleA2/@activity/@ownedActivityNode.1/@storyPattern/@constraints.4" attributeValueConstraints="//Rules/ruleA2/@activity/@ownedActivityNode.1/@storyPattern/@constraints.5" name="a1_val_prime">
              <type href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
            </variables>
            <variables xsi:type="AttributeConstraints:PrimitiveVariable" cspConstraints="//Rules/ruleA2/@activity/@ownedActivityNode.1/@storyPattern/@constraints.4" attributeValueConstraints="//Rules/ruleA2/@activity/@ownedActivityNode.1/@storyPattern/@constraints.6" name="a2_val">
              <type href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
            </variables>
          </storyPattern>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StopNode" incoming="//Rules/ruleA2/@activity/@ownedActivityEdge.1"/>
        <ownedActivityEdge source="//Rules/ruleA2/@activity/@ownedActivityNode.0" target="//Rules/ruleA2/@activity/@ownedActivityNode.1"/>
        <ownedActivityEdge source="//Rules/ruleA2/@activity/@ownedActivityNode.1" target="//Rules/ruleA2/@activity/@ownedActivityNode.2"/>
      </activity>
    </eOperations>
    <eOperations xsi:type="activities:MoflonEOperation" name="ruleB2">
      <eParameters name="fx">
        <eType xsi:type="ecore:EClass" href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//Feature"/>
      </eParameters>
      <activity owningOperation="//Rules/ruleB2">
        <ownedActivityNode xsi:type="activities:StartNode" outgoing="//Rules/ruleB2/@activity/@ownedActivityEdge.0"/>
        <ownedActivityNode xsi:type="activities:StoryNode" name="ActivityNode2" comment="ActivityNode2" outgoing="//Rules/ruleB2/@activity/@ownedActivityEdge.1" incoming="//Rules/ruleB2/@activity/@ownedActivityEdge.0">
          <storyPattern comment="ActivityNode2">
            <objectVariable name="fx" outgoingLink="//Rules/ruleB2/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.0" bindingState="BOUND">
              <type xsi:type="ecore:EClass" href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//Feature"/>
            </objectVariable>
            <objectVariable name="ax" incomingLink="//Rules/ruleB2/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.0">
              <type xsi:type="ecore:EClass" href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//RealFeatureAttribute"/>
            </objectVariable>
            <linkVariable name="real" target="//Rules/ruleB2/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.1" source="//Rules/ruleB2/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.0">
              <type href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//Feature/real"/>
            </linkVariable>
            <constraints xsi:type="AttributeConstraints:CspConstraint" parameters="//Rules/ruleB2/@activity/@ownedActivityNode.1/@storyPattern/@variables.0 //Rules/ruleB2/@activity/@ownedActivityNode.1/@storyPattern/@variables.1 //Rules/ruleB2/@activity/@ownedActivityNode.1/@storyPattern/@variables.2" name="*"/>
            <constraints xsi:type="AttributeConstraints:AssignmentConstraint" parameter="//Rules/ruleB2/@activity/@ownedActivityNode.1/@storyPattern/@variables.0" objectVariable="//Rules/ruleB2/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.1">
              <type href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//RealFeatureAttribute/val"/>
            </constraints>
            <constraints xsi:type="AttributeConstraints:AttributeLookupConstraint" parameter="//Rules/ruleB2/@activity/@ownedActivityNode.1/@storyPattern/@variables.1" objectVariable="//Rules/ruleB2/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.1">
              <type href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//RealFeatureAttribute/val"/>
            </constraints>
            <variables xsi:type="AttributeConstraints:PrimitiveVariable" cspConstraints="//Rules/ruleB2/@activity/@ownedActivityNode.1/@storyPattern/@constraints.0" attributeValueConstraints="//Rules/ruleB2/@activity/@ownedActivityNode.1/@storyPattern/@constraints.1" name="ax_val_prime">
              <type href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
            </variables>
            <variables xsi:type="AttributeConstraints:PrimitiveVariable" cspConstraints="//Rules/ruleB2/@activity/@ownedActivityNode.1/@storyPattern/@constraints.0" attributeValueConstraints="//Rules/ruleB2/@activity/@ownedActivityNode.1/@storyPattern/@constraints.2" name="ax_val">
              <type href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
            </variables>
            <variables xsi:type="AttributeConstraints:LiteralVariable" cspConstraints="//Rules/ruleB2/@activity/@ownedActivityNode.1/@storyPattern/@constraints.0" name="0.1">
              <type href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
            </variables>
          </storyPattern>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StopNode" incoming="//Rules/ruleB2/@activity/@ownedActivityEdge.1"/>
        <ownedActivityEdge source="//Rules/ruleB2/@activity/@ownedActivityNode.0" target="//Rules/ruleB2/@activity/@ownedActivityNode.1"/>
        <ownedActivityEdge source="//Rules/ruleB2/@activity/@ownedActivityNode.1" target="//Rules/ruleB2/@activity/@ownedActivityNode.2"/>
      </activity>
    </eOperations>
    <eOperations xsi:type="activities:MoflonEOperation" name="ruleC2">
      <eParameters name="fy">
        <eType xsi:type="ecore:EClass" href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//Feature"/>
      </eParameters>
      <activity owningOperation="//Rules/ruleC2">
        <ownedActivityNode xsi:type="activities:StartNode" outgoing="//Rules/ruleC2/@activity/@ownedActivityEdge.0"/>
        <ownedActivityNode xsi:type="activities:StoryNode" name="ActivityNode3" comment="ActivityNode3" outgoing="//Rules/ruleC2/@activity/@ownedActivityEdge.1" incoming="//Rules/ruleC2/@activity/@ownedActivityEdge.0">
          <storyPattern comment="ActivityNode3">
            <objectVariable name="fy" outgoingLink="//Rules/ruleC2/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.0" bindingState="BOUND">
              <type xsi:type="ecore:EClass" href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//Feature"/>
            </objectVariable>
            <objectVariable name="ay" incomingLink="//Rules/ruleC2/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.0">
              <type xsi:type="ecore:EClass" href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//RealFeatureAttribute"/>
            </objectVariable>
            <linkVariable name="real" target="//Rules/ruleC2/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.1" source="//Rules/ruleC2/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.0">
              <type href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//Feature/real"/>
            </linkVariable>
            <constraints xsi:type="AttributeConstraints:CspConstraint" parameters="//Rules/ruleC2/@activity/@ownedActivityNode.1/@storyPattern/@variables.0 //Rules/ruleC2/@activity/@ownedActivityNode.1/@storyPattern/@variables.1 //Rules/ruleC2/@activity/@ownedActivityNode.1/@storyPattern/@variables.2" name="+"/>
            <constraints xsi:type="AttributeConstraints:AttributeLookupConstraint" parameter="//Rules/ruleC2/@activity/@ownedActivityNode.1/@storyPattern/@variables.0" objectVariable="//Rules/ruleC2/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.1">
              <type href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//RealFeatureAttribute/val"/>
            </constraints>
            <constraints xsi:type="AttributeConstraints:AssignmentConstraint" parameter="//Rules/ruleC2/@activity/@ownedActivityNode.1/@storyPattern/@variables.1" objectVariable="//Rules/ruleC2/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.1">
              <type href="platform:/plugin/org.moflon.maave.tests.lang.featuremodel/model/Featuremodel.ecore#//RealFeatureAttribute/val"/>
            </constraints>
            <variables xsi:type="AttributeConstraints:PrimitiveVariable" cspConstraints="//Rules/ruleC2/@activity/@ownedActivityNode.1/@storyPattern/@constraints.0" attributeValueConstraints="//Rules/ruleC2/@activity/@ownedActivityNode.1/@storyPattern/@constraints.1" name="ay_val">
              <type href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
            </variables>
            <variables xsi:type="AttributeConstraints:PrimitiveVariable" cspConstraints="//Rules/ruleC2/@activity/@ownedActivityNode.1/@storyPattern/@constraints.0" attributeValueConstraints="//Rules/ruleC2/@activity/@ownedActivityNode.1/@storyPattern/@constraints.2" name="ay_val_prime">
              <type href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
            </variables>
            <variables xsi:type="AttributeConstraints:LiteralVariable" cspConstraints="//Rules/ruleC2/@activity/@ownedActivityNode.1/@storyPattern/@constraints.0" name="10">
              <type href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
            </variables>
          </storyPattern>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StopNode" incoming="//Rules/ruleC2/@activity/@ownedActivityEdge.1"/>
        <ownedActivityEdge source="//Rules/ruleC2/@activity/@ownedActivityNode.0" target="//Rules/ruleC2/@activity/@ownedActivityNode.1"/>
        <ownedActivityEdge source="//Rules/ruleC2/@activity/@ownedActivityNode.1" target="//Rules/ruleC2/@activity/@ownedActivityNode.2"/>
      </activity>
    </eOperations>
  </eClassifiers>
</ecore:EPackage>
