<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:activities="platform:/plugin/SDMLanguage/model/SDMLanguage.ecore#//activities" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="constraintlib" nsURI="platform:/plugin/org.moflon.maave.tool.smt.constraintlib/model/Constraintlib.ecore" nsPrefix="org.moflon.maave.tool.smt.constraintlib">
  <eClassifiers xsi:type="ecore:EClass" name="SMTConstraintLibrary">
    <eOperations xsi:type="activities:MoflonEOperation" name="lookupPredicateSpecification" eType="//PredicateSpecification">
      <eParameters name="predicate">
        <eType xsi:type="ecore:EClass" href="platform:/plugin/org.moflon.maave.tool.symbolicgraphs/model/Symbolicgraphs.ecore#//SymbolicGraphs/Predicate"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="predicateSpecifications" upperBound="-1" eType="//PredicateSpecification" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="smtLibPredicateSpecifications" upperBound="-1" eType="//SMTLibPredicateSpecification" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PredicateSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterTypes" upperBound="-1" eType="//ParameterType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="smtLibPredicateSpecification" eType="//SMTLibPredicateSpecification" eOpposite="//SMTLibPredicateSpecification/predicateSpecifications"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbol" ordered="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eDataType">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EDataType"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SMTLibPredicateSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="predicateSpecifications" upperBound="-1" eType="//PredicateSpecification" eOpposite="//PredicateSpecification/smtLibPredicateSpecification"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="smtLibString" ordered="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
